### ISSUE TITLE
Ready to merge - Still not accepted 4 days 

### ISSUE THREAD

**Issue by ashwinraiyani** [education/GitHubGraduation-2021#10014]
4 Days passed but still not PR not merged.

**Comment by katelyn98** [comment]
If you close your pull request and open a new one it will go through. My pull request was originally in the 3000s as well but I had errors. I fixed the errors but it still wouldn't say it was ready to merge. So I closed the pull request, opened a new one, and it went through review right away and is marked as ready to merge now. Try that!

**Comment by pasindujr** [comment]
Hi @ashwinraiyani, the last PR that got merged was 7383.
What is your PR number?

**Comment by merrcury** [comment]
GitHub Education Team is on holiday and will start reviewing them on Friday if You have submitted them on 14 May or before for Swag Eligibility.  For Yearbook, They still be merging those but will take time

**Comment by ValchanOficial** [comment]
Same here https://github.com/education/GitHubGraduation-2021/pull/8345
I'll wait as @merrcury told

**Comment by elisemoe** [comment]
Our team will get through all pull requests with the “ready to merge” label before May 27 ✨
