### ISSUE TITLE
PR submitted 4 days ago and it has a tag of ready to merge, still not merged

### ISSUE THREAD

**Issue by chaharnishant11** [education/GitHubGraduation-2021#10068]
My PR #7970 has not been merged and i had submitted it way before 5000 PRs were merged. 

It got the ready to merge tag just after a few minutes.

**Comment by rqatia** [comment]
me too

**Comment by elisemoe** [comment]
Our team will get through all pull requests with the “ready to merge” label before May 27 ✨
