### ISSUE TITLE
PR hasn't been merged for 7 days 

### ISSUE THREAD

**Issue by taylorylee** [education/GitHubGraduation-2021#10129]
Hi, I am writing an issue to let the GitHub team know that my PR hasn't been merged for a week. https://github.com/taylorylee/GitHubGraduation-2021/pull/1 All the criteria and checklist were met 

Thank you so much for creating this project! Let me know if there's anything else I need to do.

**Comment by chirag-jn** [comment]
You made the PR on your forked repository. You had to make a PR on the original repository.

**Comment by taylorylee** [comment]
Hi @chirag-jn! I believe it went through now. Thank you for your comment.
