### ISSUE TITLE
Pull Request Never Reviewed

### ISSUE THREAD

**Issue by da-stoi** [education/GitHubGraduation-2021#1015]
Hey GitHub Education Team!

First off, I would like to say thank you for doing this for the graduating class of 2021, I think I can speak for most people when I saw we greatly appreciate it.

I was hoping someone could manually look over [my PR](https://github.com/education/GitHubGraduation-2021/pull/902). When I first submitted it it seemed to have passed all the checks but never got the "✅ Ready for Merge" tag since it was awaiting review. I then went ahead and updated my quote and now it seems to be stuck in the checking stage with no feedback if I need to change something.

I would greatly appreciate if someone could take a look at this and offer some insight about what needs to be done to make sure I can be part of the 2021 Yearbook.

**Comment by ArpitArunKumaar** [comment]
hey, i can see you didn't perform the checks (I ain't any from the github team tho)

**Comment by ArpitArunKumaar** [comment]
> hey, i can see you didn't perform the checks (I ain't any from the github team tho)

I faced the same issue but then closed that pr and created a new one

**Comment by da-stoi** [comment]
> hey, i can see you didn't perform the checks (I ain't any from the github team tho)

I did do all the checks and my initial commit said that it passed all the checks. It was just waiting for someone to approve it.

**Comment by ArpitArunKumaar** [comment]
![Screen Shot 2021-05-12 at 9 57 42 PM](https://user-images.githubusercontent.com/54761690/118022191-21836b00-b36d-11eb-90bd-4b09fd1e2bf8.png)

**Comment by ArpitArunKumaar** [comment]
> > hey, i can see you didn't perform the checks (I ain't any from the github team tho)
> 
> I did do all the checks and my initial commit said that it passed all the checks. It was just waiting for someone to approve it.

prolly just create a new one to avoid any confusion

**Comment by da-stoi** [comment]
The original one passed and I changed nothing besides adding a quote, that's why I'm confused on what I need to do.

**Comment by ArpitArunKumaar** [comment]
> The original one passed and I changed nothing besides adding a quote, that's why I'm confused on what I need to do.

just close your current PR and create a new one
![Screen Shot 2021-05-12 at 10 02 15 PM](https://user-images.githubusercontent.com/54761690/118022726-b9815480-b36d-11eb-8df0-163352c759cb.png)
also, it's cuz you've 2 commits in the .md file

**Comment by da-stoi** [comment]
So I just made a [new one](https://github.com/education/GitHubGraduation-2021/pull/1064) and it seems to still be doing it.
![Screen Shot 2021-05-12 at 11 07 22 AM](https://user-images.githubusercontent.com/20031472/118023328-48f91a00-b312-11eb-99c6-c763d600aaa0.png)

**Comment by wick3ds0ul** [comment]
![image](https://user-images.githubusercontent.com/48680692/118032432-4d124f80-b385-11eb-86eb-e160d8a44cbc.png)
Does this mean PR has been merged? Its been a while

**Comment by Zubair-12** [comment]
No @wick3ds0ul PR is not merged.

**Comment by wick3ds0ul** [comment]
@Zubair-12 am I missing something?

**Comment by Zubair-12** [comment]
No the owner will review and merge it.

**Comment by D-HackCoder** [comment]
> No the owner will review and merge it.
but I think if you will in 5k then only..!

**Comment by nabanita-sarkar** [comment]
> So I just made a [new one](https://github.com/education/GitHubGraduation-2021/pull/1064) and it seems to still be doing it.
> ![Screen Shot 2021-05-12 at 11 07 22 AM](https://user-images.githubusercontent.com/20031472/118023328-48f91a00-b312-11eb-99c6-c763d600aaa0.png)

I am stuck in same condition

**Comment by elisemoe** [comment]
🤔 Thanks for letting us know! 

It looks like the bot was never added to your PR. We're looking into why. As a workaround (and for anyone having similar issues), I've manually requested the bot review your pull request.

![Screen Shot 2021-05-12 at 1 08 08 PM](https://user-images.githubusercontent.com/6633808/118037914-4e129500-b323-11eb-9e80-73ac24eba228.png)

**Comment by calebchiam** [comment]
@elisemoe Could you add the bot to review my PR as well? #4103. Thank you!

**Comment by elisemoe** [comment]
> 🤔 Thanks for letting us know!
> 
> It looks like the bot was never added to your PR. We're looking into why. As a workaround (and for anyone having similar issues), I've manually requested the bot review your pull request.
> 
> ![Screen Shot 2021-05-12 at 1 08 08 PM](https://user-images.githubusercontent.com/6633808/118037914-4e129500-b323-11eb-9e80-73ac24eba228.png)

Update: even with the manually requested review, it still seems to be having having trouble. We're looking into this now!

**Comment by da-stoi** [comment]
> > 🤔 Thanks for letting us know!
> > It looks like the bot was never added to your PR. We're looking into why. As a workaround (and for anyone having similar issues), I've manually requested the bot review your pull request.
> > ![Screen Shot 2021-05-12 at 1 08 08 PM](https://user-images.githubusercontent.com/6633808/118037914-4e129500-b323-11eb-9e80-73ac24eba228.png)
> 
> Update: even with the manually requested review, it still seems to be having having trouble. We're looking into this now!

@elisemoe Thank you for looking into this!

**Comment by D-HackCoder** [comment]
@elisemoe why my data is not showing in the main branch..?

**Comment by nabanita-sarkar** [comment]
> 🤔 Thanks for letting us know!
> 
> It looks like the bot was never added to your PR. We're looking into why. As a workaround (and for anyone having similar issues), I've manually requested the bot review your pull request.
> 
> ![Screen Shot 2021-05-12 at 1 08 08 PM](https://user-images.githubusercontent.com/6633808/118037914-4e129500-b323-11eb-9e80-73ac24eba228.png)

Can you please look into my pull request too [4512](https://github.com/education/GitHubGraduation-2021/pull/4512#issue-643455041)

**Comment by da-stoi** [comment]
> @elisemoe why my data is not showing in the main branch..?

If yours has been Approved and marked as "✅ Ready for Merge" then you're fine. Just be patient.

**Comment by D-HackCoder** [comment]
> > @elisemoe why my data is not showing in the main branch..?
> 
> If yours has been Approved and marked as "✅ Ready for Merge" then you're fine. Just be patient.

yes it is showing like this okay I'm waiting

**Comment by ojasvishaklya** [comment]
> > So I just made a [new one](https://github.com/education/GitHubGraduation-2021/pull/1064) and it seems to still be doing it.
> > ![Screen Shot 2021-05-12 at 11 07 22 AM](https://user-images.githubusercontent.com/20031472/118023328-48f91a00-b312-11eb-99c6-c763d600aaa0.png)
> 
> I am stuck in same condition

does this condition mean there's an error or we just need wait

**Comment by da-stoi** [comment]
@ojasvishaklya 
Yeah, you seem to be in the same boat as me. I guess we just need to wait to hear back from @elisemoe.

**Comment by ojasvishaklya** [comment]
>  Thanks for letting us know!
> 
> It looks like the bot was never added to your PR. We're looking into why. As a workaround (and for anyone having similar issues), I've manually requested the bot review your pull request.
> 
> ![Screen Shot 2021-05-12 at 1 08 08 PM](https://user-images.githubusercontent.com/6633808/118037914-4e129500-b323-11eb-9e80-73ac24eba228.png)

could you please add a review bot to #3135

**Comment by YKakdas** [comment]
@elisemoe Same happened to my pr #3256, bot never added.

**Comment by nabanita-sarkar** [comment]
> 🤔 Thanks for letting us know!
> 
> It looks like the bot was never added to your PR. We're looking into why. As a workaround (and for anyone having similar issues), I've manually requested the bot review your pull request.
> 
> ![Screen Shot 2021-05-12 at 1 08 08 PM](https://user-images.githubusercontent.com/6633808/118037914-4e129500-b323-11eb-9e80-73ac24eba228.png)

Can you please add a review bot to my pr too [4512](https://github.com/education/GitHubGraduation-2021/pull/4512#issue-643455041).

**Comment by sandyskim** [comment]
> 🤔 Thanks for letting us know!
> 
> It looks like the bot was never added to your PR. We're looking into why. As a workaround (and for anyone having similar issues), I've manually requested the bot review your pull request.
> 
> ![Screen Shot 2021-05-12 at 1 08 08 PM](https://user-images.githubusercontent.com/6633808/118037914-4e129500-b323-11eb-9e80-73ac24eba228.png)

hi, i believe i'm having the same issue with my pr, #4817 😢 thank you in advance! 😀

**Comment by nehamehta2110** [comment]
@elisemoe I am seeing a similar issue with my PR #3251

**Comment by xnikitin** [comment]
@elisemoe I am seeing a similar issue with my PR #5098

**Comment by da-stoi** [comment]
@elisemoe Thank you so much for your help, my Pull Request just got approved and is ready to merge. 🎉  🎓 

I am wondering, if for some reason I don't get in as first 5000 is there anyway to appeal that since the issue was out of my control?

**Comment by ndm767** [comment]
@elisemoe I'm having the same issue with my PR  #3343
