### ISSUE TITLE
confirmation required!

### ISSUE THREAD

**Issue by zaibidev** [education/GitHubGraduation-2021#10211]
Is my commit accepted or not?? if not then u may proceed through link:

https://github.com/zaibidev/GitHubGraduation-2021

**Comment by chaitanyasjoshi** [comment]
Hi @zaibidev 
Your pull request is not merged. I see you have opened multiple pull requests. I will suggest close all the previous pull requests and create a new one.
You have done everything right #9856 here. 
Just use this template when creating your markdown file. (You are missing --- at the beginning of the file)
```
---
name: FULLNAME-OR-NICKNAME # No longer than 28 characters
institution: INSTITUTION-NAME 🚩 # no longer than 58 characters
quote: YOUR-SENIOR-QUOTE # no longer than 100 characters, avoid using quotes(") to guarantee the format remains the same.
github_user: YOUR-GITHUB-USERNAME
---
```
