### ISSUE TITLE
Name not Displaying 

### ISSUE THREAD

**Issue by Tagsahil** [education/GitHubGraduation-2021#10340]
My PR was merged and I got mail related to that but the folder that belongs to my Username which I created is not showing in the _data folder.
https://github.com/education/GitHubGraduation-2021/pull/2551#partial-pull-merging

**Comment by RupomChowdhury** [comment]
here it is-- [https://github.com/education/GitHubGraduation-2021/tree/main/_data/Tagsahil](
GitHubGraduation-2021/_data/Tagsahil)

**Comment by RupomChowdhury** [comment]
@Tagsahil here it is -- [https://github.com/education/GitHubGraduation-2021/tree/main/_data/Tagsahil/](url)

**Comment by RupomChowdhury** [comment]
@Tagsahil here it is -- https://github.com/education/GitHubGraduation-2021/tree/main/_data/Tagsahil

**Comment by Tagsahil** [comment]
Thanks
