### ISSUE TITLE
Update on Swag

### ISSUE THREAD

**Issue by omkarkd** [education/GitHubGraduation-2021#10351]
Have anyone received the swags for graduation 2021??

**Comment by RupomChowdhury** [comment]
maybe i will not qualify for that because of late pull request. but they will give the swags shipping update in readme file..

**Comment by disantana** [comment]
> Have anyone received the swags for graduation 2021??
> 

Not yet for me.

**Comment by Sangu80** [comment]
> Have anyone received the swags for graduation 2021??

not yet !

**Comment by hruday-tej** [comment]
i havent recieved any tracking status as well, did anyone of you get the shipment tracking info?

**Comment by adityaj48** [comment]
same goes for me too no lead

**Comment by gokayay** [comment]
same here

**Comment by elisemoe** [comment]
Swag is in production :) It will be a few weeks until everything is printed and we'll let you know in the repository as soon as things have shipped out!
