### ISSUE TITLE
Can I change my quote?

### ISSUE THREAD

**Issue by ArpitArunKumaar** [education/GitHubGraduation-2021#10359]
I wrote a quote that I didn't intend to submit, thinking it could be changed later. Can I change it now by any chance?

**Comment by ArpitArunKumaar** [comment]
@elisemoe

**Comment by ArpitArunKumaar** [comment]
@juanpflores

**Comment by elisemoe** [comment]
Unfortunately we can't change quotes at this time, as we have already built the graduate walk.

**Comment by elisemoe** [comment]
If you'd like to submit a pull request, I can merge and we may be able to deploy yearbook again after the event!
