### ISSUE TITLE
PR not merged

### ISSUE THREAD

**Issue by piyushP7pravin** [education/GitHubGraduation-2021#10368]
I have github student developer pack approval but my PR is not merged for the swag list.

**Comment by henryStelle** [comment]
> Submissions to the repository are closed as of 12:00pm PT.

Per the last update in the [readme](https://github.com/education/GitHubGraduation-2021/blob/main/README.md), the repository is now closed.

**Comment by piyushP7pravin** [comment]
I have opened the PR #527 on 12th May,

**Comment by RupomChowdhury** [comment]
> 
> 
> I have opened the PR #527 on 12th May,

A minor fault from your side! You updated the file: https://github.com/education/GitHubGraduation-2021/pull/527/commits/f06d856ffab0f7fdd53f366a948001ecc7d25bca . But you didn't request a review from the @GitHub-Education-bot . 😢 
For example, check my PR https://github.com/education/GitHubGraduation-2021/pull/10330 . Whenever I edited/updated my file : requested a review!

**Comment by elisemoe** [comment]
As mentioned, the repository closed for reviews on May 27 and the event has concluded.
