### ISSUE TITLE
Name not showing on yearbook 2021

### ISSUE THREAD

**Issue by phuongnguyen0610** [education/GitHubGraduation-2021#10364]
Hello, my name is not showed on yearbook 2021. Please help!

**Comment by RupomChowdhury** [comment]
@phuongnguyen0610 what was your PR number?

**Comment by phuongnguyen0610** [comment]
539f9fc368f26f912d81c3e19c8590e55f466b3f

**Comment by phuongnguyen0610** [comment]
![image](https://user-images.githubusercontent.com/9458585/120709458-bad80580-c471-11eb-996a-d68643c5df4f.png)

**Comment by RupomChowdhury** [comment]
@phuongnguyen0610 according to this link [ https://github.com/phuongnguyen0610/GitHubGraduation-2021/pull/1 ] . I think you didn't request any pull in [ https://github.com/education/GitHubGraduation-2021 ] this repository. you merged your pr in your own forked repository and I'm still asking your PR number. You can check my PR number for example [ https://github.com/education/GitHubGraduation-2021/pull/10330 ] ...  either there no pr from your side or the pr wasn't merged.

**Comment by phuongnguyen0610** [comment]
#10365

**Comment by RupomChowdhury** [comment]
@phuongnguyen0610 yp.. now it looks perfect. but maybe it's late.  hope they'll merge those pending PR.

**Comment by RupomChowdhury** [comment]
@elisemoe any news or update for new/pending PR (ready for merge) ?

**Comment by phuongnguyen0610** [comment]
Thank you very much !
