### ISSUE TITLE
My PR is still pending  

### ISSUE THREAD

**Issue by soumik2012** [education/GitHubGraduation-2021#10360]
![image](https://user-images.githubusercontent.com/66599363/120588716-4727ff80-c455-11eb-86a2-4aa0782ff399.png)

it is before the 14 may still not merge and github bot saying the I am not eligible for swag.

**Comment by soumik2012** [comment]
@elisemoe @juanpflores please check my issue

**Comment by elisemoe** [comment]
Hi @soumik2012 👋Submissions to the Yearbook closed on May 27. Both of your PRs received the "Ready to merge" label after this date.
