### ISSUE TITLE
My name has disappeared from Yearbook

### ISSUE THREAD

**Issue by ShehanSanjula** [education/GitHubGraduation-2021#10370]
According to [PR](https://github.com/education/GitHubGraduation-2021/pull/6943), it says I am a part of the class of 2021! But I couldn't see my name on the [Yearbook 2021](https://education.github.com/graduation/yearbook?sort=az). Is there something wrong? Please help!

**Comment by arrbxr** [comment]
@ShehanSanjula 
here is your name:- [Yearbook 2021](https://education.github.com/graduation/yearbook?sort=az&page=19&search=ShehanSanjula#ShehanSanjula)

**Comment by ShehanSanjula** [comment]
Thank you very much! @arrbxr 🙌
