### ISSUE TITLE
I can't see my name.

### ISSUE THREAD

**Issue by juanfvilla** [education/GitHubGraduation-2021#10375]
I review the list in graduation Book and I am not appear. What happen? Could you please explain me? Thanks in advance.

**Comment by nilsonsales** [comment]
You're in the list: https://education.github.com/graduation/yearbook?sort=az&page=44&search=juanfvilla#juanfvilla

**Comment by RupomChowdhury** [comment]
you are in man! :f take a look https://education.github.com/graduation/yearbook?sort=az&page=44&search=juanfvilla#juanfvilla
