### ISSUE TITLE
Checking eligibility for future GitHub Graduation Year books

### ISSUE THREAD

**Issue by VaibhavBhand** [education/GitHubGraduation-2021#10371]
I wanted to part be a part of GitHubGraduation 2021 as in year of my B.Tech. graduation. Unfortunately it didn't work out. But can still be part of GitHubGraduation yearbook 2023, year of M.Tech graduation?
It would awesome experience and honourous experience to be includefd in GitHub yearbook.

**Comment by elisemoe** [comment]
Yes! You're welcome to join future events 💖
