### ISSUE TITLE
I Changed My user Name

### ISSUE THREAD

**Issue by Tusker13-04** [education/GitHubGraduation-2021#10373]
My previous user name was DragonKing13-04  now it has been changed to Tusker13-04

**Comment by nilsonsales** [comment]
You're in the list: https://education.github.com/graduation/yearbook?sort=az&page=44&search=juanfvilla#juanfvilla

**Comment by vasudev-sharma** [comment]
Same here I too changed my user name from **@vs74** to **@vasudev-sharma**. My PR has been merged with my old username.

May I know would it create any problem? If yes, should I create another PR?

**Comment by elisemoe** [comment]
Thank-you both for letting us know! I've updated the information on our side.
