### ISSUE TITLE
Can't see my name in the yearbook 2021

### ISSUE THREAD

**Issue by rahuldey613** [education/GitHubGraduation-2021#10378]
#325 was merged successfully still I cant  see my name in the yearbook 2021, Why is that?

**Comment by RupomChowdhury** [comment]
then what's that bro? 😕 https://education.github.com/graduation/yearbook?sort=az&page=55&search=rahuldey613#rahuldey613

**Comment by rahuldey613** [comment]
Thanks for getting me noticed.
