### ISSUE TITLE
How can one see or edit the shipment information that was submitted through the form?

### ISSUE THREAD

**Issue by Snipeur060** [education/GitHubGraduation-2021#10388]
How can one see or edit the shipment information that was submitted through the form?

**Comment by theharshrastogi** [comment]
There is no update till now, it's just in 2-3 weeks will delivered in USA. They have till when it will be delivered in other countries. But they said assured us.

**Comment by elisemoe** [comment]
you can submit your updated shipping information here by the end of day please. https://airtable.com/shrZuXu2OKrxO6PiD

**Comment by Snipeur060** [comment]
yes i submit now
