### ISSUE TITLE
Not showing?

### ISSUE THREAD

**Issue by 4po** [education/GitHubGraduation-2021#10393]
[4po.md](https://github.com/education/GitHubGraduation-2021/files/6642934/4po.md)

---
name: Leonhart Bukovski
institution: thecodingmachine
quote: French-Man ! We L0V3 Baguettes ;)
github_user: 4po
---

**Comment by varghesejose2020** [comment]
What is your PR number

**Comment by adnamaric** [comment]
@4po You forked copy of graduation repository from some random user instead of forking it directly from education/GitHubGraduation-2021, and that's the reason you can't see your pull request among other requests.

**Comment by Rajat-Jain29** [comment]
Is anyone received swag those who are in top 5000 PRs ?

**Comment by asifrasheed6** [comment]
> Is anyone received swag those who are in top 5000 PRs ?

I don't think they have shipped it yet. I guess they'll update it on the README or on Twitter when they does.

**Comment by Rajat-Jain29** [comment]
@varghesejose2020 what's the number of your PR ?

**Comment by asifrasheed6** [comment]
> @varghesejose2020 what's the number of your PR ?

144

**Comment by varghesejose2020** [comment]
😊👍  @asifrasheed6

> > @varghesejose2020 what's the number of your PR ?
> 
> 144

**Comment by adityaj48** [comment]
still waiting for it
