### ISSUE TITLE
update regarding shipment

### ISSUE THREAD

**Issue by adityaj48** [education/GitHubGraduation-2021#10396]
anybody has any idea, till when we are getting it (expected time)

**Comment by adavijit** [comment]
@elisemoe Please share update on this

**Comment by kavyanshpandey** [comment]
I have not received any card on email and also haven't received swags yet.

**Comment by Pavankalyannvs** [comment]
Don't know but everyone is eagerly waiting for swags😅

**Comment by faizalanwar** [comment]
I hope no one is disappointed

**Comment by Anshtalwar360** [comment]
Is there any update?

**Comment by harshgupta20** [comment]
Do people who did register for 2020 class got the swags ?
If not then there is no chance of giving the swags for our batch(2021).

**Comment by adavijit** [comment]
@harshgupta20 nope! Swag is in production and it will be a few weeks until everything is printed

**Comment by harshgupta20** [comment]
@adavijit Thanks for the info. but how you know it ?

**Comment by adavijit** [comment]
@harshgupta20 
->https://github.com/education/GitHubGraduation-2021/issues/10351#issuecomment-853050747

**Comment by D-Studios** [comment]
What date will we get swag from participating?

**Comment by D-Studios** [comment]
What date will we get swag?

**Comment by elisemoe** [comment]
Hello 👋 Congrats everyone on your graduation! Swag is still in production. We don't have an estimated ship date just yet but we will update the Graduation repository readme as soon as we do!
 
Thanks for your patience 💖
