### ISSUE TITLE
Update regarding swag shipment

### ISSUE THREAD

**Issue by adavijit** [education/GitHubGraduation-2021#10409]
@elisemoe 

If the swag shipment has already been processed please update on Readme file. Here everyone is coming to check update on shipment of swag. Please make it clear to everyone. Also let us know the tracking process of the shipment.

**Comment by yashsrivastava16** [comment]
@elisemoe yes please make an update

**Comment by hruday-tej** [comment]
Are they rolling out any Email when your swag is shipped and ready to be delivered?

**Comment by elisemoe** [comment]
We've had a few delays with production but swag is still in the works! Thanks for your patience 💖

**Comment by adavijit** [comment]
@elisemoe , It would be so nice if you share any update with us
