### ISSUE TITLE
Possibility of Updating Shipping Address

### ISSUE THREAD

**Issue by srishtidh** [education/GitHubGraduation-2021#10407]
Hello,

I will be moving due to personal circumstances, and wanted to check if it is still possible to update the shipping address I submitted through the original form.

Thanks!
Srishti

**Comment by dyl10s** [comment]
I actually am in the same situation and would love to know!

**Comment by MaheshBabu11** [comment]
You could enter the new address in the text field in the form linked below according to a reply from @elisemoe in another issue.
https://airtable.com/shrZuXu2OKrxO6PiD

**Comment by srishtidh** [comment]
Thanks a lot for the link @MaheshBabu11!

I noticed that form in the other issue, but wasn't sure if they're still accepting changes through that.

Would be great to hear from the Education team!

**Comment by alexkjoseph** [comment]
> You could enter the new address in the text field in the form linked below according to a reply from @elisemoe in another issue.
> https://airtable.com/shrZuXu2OKrxO6PiD

I am sorry to disturb everyone. @MaheshBabu11  should I complete this form inorder to recieve swags

**Comment by MaheshBabu11** [comment]
No, @alexkjoseph  This form is for those who wish to change their shipping address but I'm not sure if they're still accepting changes through that.
