### ISSUE TITLE
When are the Swags Shipping?

### ISSUE THREAD

**Issue by srinidhibhat45** [education/GitHubGraduation-2021#10416]
would like to know when the swags will ship :/

**Comment by blackmarketer** [comment]
Yeah same here! it's been already month waiting for updates:(

**Comment by jvjvalerio** [comment]
any updates on swag shipment?

**Comment by Ankur-Khandelwal** [comment]
Yes, it has been months now

**Comment by Reprevise** [comment]
Yeah, would really like to know. Been waiting 3 months.

**Comment by Ankur-Khandelwal** [comment]
@elisemoe

**Comment by erikizan** [comment]
Have not received anything either 😭, was really looking forward to the merch :/

**Comment by karakolodinsky** [comment]
Just remembered this, any updates???

**Comment by thisispratt** [comment]
Sad to see that there are no updates on the swag. 😞 @elisemoe
