### ISSUE TITLE
Please Update the readme!

### ISSUE THREAD

**Issue by Rishav1212** [education/GitHubGraduation-2021#10421]
It's almost a quarter. Still no update. Can you please tell us that when are we going to receive the swags :)

**Comment by nitish-awasthi** [comment]
@elisemoe @juanpflores

**Comment by faizalanwar** [comment]
Maybe we will have to wait until December, this information listed in the FAQ, [Here](https://education.github.com/graduation/faq)

**Comment by nfl0** [comment]
i think it will be distributed in the form of NFTs

**Comment by elisemoe** [comment]
Swag has shipped 🎉

https://github.com/education/GitHubGraduation-2021/blob/main/README.md
