### ISSUE TITLE
Dear Github Graduation Team, Can you please show the same enthusiasm that you were showing before 5 June 2021. So that we don't consider this event as spam.

### ISSUE THREAD

**Issue by nitish-awasthi** [education/GitHubGraduation-2021#10423]
@elisemoe @juanpflores

**Comment by elisemoe** [comment]
Hey @nitish-awasthi! This is our favorite event of the year and I promise we're as enthusiastic as ever behind the scenes 💖 Production has faced a few delays and we've had to go through some redesign to get things to the level we want to share with all of you. As soon as the cards have been printed and confirmed to ship soon, we will let you all know. Thanks for your patience.
