### ISSUE TITLE
Update Shipping Address

### ISSUE THREAD

**Issue by akksshah** [education/GitHubGraduation-2021#10424]
@elisemoe Is there any way we can update the shipping address. I understand that the cards have not been printed and hence wondered if there was a possibility to update the shipping address. I would really appreciate it

**Comment by elisemoe** [comment]
Yes! Please submit your updated address in the Notes field of [the question form](https://airtable.com/shrZuXu2OKrxO6PiD).

**Comment by akksshah** [comment]
Hi @elisemoe , was the address update successful?

**Comment by elisemoe** [comment]
Hi @akksshah 👋 address updates should have been successful! But if you still haven't received your trading card, please fill out the replacement form just in case.

https://airtable.com/shrfvURjuNzpnk48i
