### ISSUE TITLE
i didn't receive swag yet :(

### ISSUE THREAD

**Issue by pman47** [education/GitHubGraduation-2021#10428]
i didn't receive swag yet :(

_Originally posted by @pman47 in https://github.com/education/GitHubGraduation-2021/issues/6994#issuecomment-932189897_
![2021-10-3_9-58-56](https://user-images.githubusercontent.com/72241422/135739985-77d94d14-39a5-46fa-a0e2-010e82829270.PNG)

**Comment by Sanan4li** [comment]
#10422 Please check this issue and read the comments.
