### ISSUE TITLE
Any Updates

### ISSUE THREAD

**Issue by Darkshadow9799** [education/GitHubGraduation-2021#10435]
Any updates regarding swags?

@elisemoe + @juanpflores

**Comment by adavijit** [comment]
@elisemoe + @juanpflores 

Please update the shipping details with. It's been long time you haven't updated anything.
In case you have plan not to ship then please update the readme file.
Here we're coming here and checking the shipment status everyday. It does't make sense at all.

**Comment by SpooderManEXE** [comment]
following

**Comment by elisemoe** [comment]
Swag has shipped 🎉

https://github.com/education/GitHubGraduation-2021/blob/main/README.md
