### ISSUE TITLE
Blank stats?

### ISSUE THREAD

**Issue by mkwarman** [education/GitHubGraduation-2021#10442]
Hi! I just received my card, and while the picture and username look good, the statistics section of the card is blank. Just wondering if there was an issue with [my submission](https://github.com/education/GitHubGraduation-2021/pull/1520). Thank you!
![image0(1)](https://user-images.githubusercontent.com/7865063/144880343-7736f6b3-77cb-4d00-b952-0e858f0b4360.jpeg)

**Comment by Sanan4li** [comment]
@mkwarman can you share what else did you receive? if possible, share pictures. We are waiting from the last 6 months.

**Comment by nitish-awasthi** [comment]
@Sanan4li nothing else, only cards are getting delivered.

**Comment by yashsrivastava16** [comment]
> @Sanan4li nothing else, only cards are getting delivered.

Not even github logo bottle?

**Comment by cygann** [comment]
@mkwarman It looks like they printed the bio line from our profiles in the box under the picture. Since your profile doesn't have a bio, this may be why it's blank.

**Comment by mkwarman** [comment]
Great observation @cygann, indeed I now see that it even says to ensure your bio is up to date with that you want printed on the card in the GitHubGraduation-2021 repo [README.md](https://github.com/education/GitHubGraduation-2021#readme). Seems this is expected then, and I failed to RTFM 😄 

I'll go ahead and close this issue.
