### ISSUE TITLE
Got Swag-pack 🎁 in India 📦

### ISSUE THREAD

**Issue by anshobrii** [education/GitHubGraduation-2021#10445]
<h1> I am from India and I still haven't received my swag pack anyone got any info yet :(</h1>

**Comment by CrazyCoder009** [comment]
Same here

**Comment by MaheshBabu11** [comment]
I am also in India, I received the swag pack a week ago.

**Comment by anshobrii** [comment]
wow, Congrats  🎉
Btw which company delivered your Swag-Pack?

**Comment by hruday-tej** [comment]
> I am also in India, I received the swag pack a week ago.

Bro i just got 2 cards, no swag nothing

**Comment by hruday-tej** [comment]
> wow, Congrats 🎉 Btw which company delivered your Swag-Pack?

It comes through mail

**Comment by RakshaPawar108** [comment]
Even I am from India, I didn't  even get notification of swags being shipped..

**Comment by MaheshBabu11** [comment]
> Even I am from India, I didn't even get notification of swags being shipped..

You will not receive any notification. It's delivered through Indian post to your mailing address.

**Comment by pman47** [comment]
I'm also from India and didn't received yet :(

**Comment by RakshaPawar108** [comment]
> ### Today end of the day of January is also over, and till now I didn't get any notification about my "Swag Pack"
> 🚩 🏁 🎌

Same for me. They were going to release a form I guess after 31st for those who didn't receive.

**Comment by elisemoe** [comment]
If you haven't yet received your trading card, please fill out the replacement form ✨

https://github.com/education/GitHubGraduation-2021

**Comment by CrazyCoder009** [comment]
I just got my Swag pack! Thank you Github!

**Comment by anshobrii** [comment]
I didn't get any update yet .
