### ISSUE TITLE
Only cards as swag?

### ISSUE THREAD

**Issue by manoj997** [education/GitHubGraduation-2021#10444]
Hi,
I got a card today from GitHub education. But not sure if that's the only "swag" we're supposed to get.

@elisemoe Please kindly respond

**Comment by manoj997** [comment]
![IMG_20211228_095125.jpg](https://user-images.githubusercontent.com/40816448/147528453-4e2e743f-80ed-4d8c-a78e-635c8824d599.jpg)

**Comment by faizalanwar** [comment]
@manoj997 can you show me the back of the card?

**Comment by manoj997** [comment]
Trading card? Here you go..![IMG_20211228_101812.jpg](https://user-images.githubusercontent.com/40816448/147529264-881a6d5f-5d5b-48a4-9741-212768a09143.jpg)

**Comment by manoj997** [comment]
So as mentioned by @elisemoe in #10441 , The trading card is the swag. This is disappointing for most of us but that is the reality. The batch of 2020 got Github water bottles and a sticker pack but we do not deserve such "swag". 
Sad indeed. But anyway thank you so much for everyone with @education for arranging this.

Closing this.

**Comment by manoj997** [comment]
@amashi996 @Bavanraj-5 
FYI

**Comment by elisemoe** [comment]
> So as mentioned by @elisemoe in #10441 , The trading card is the swag. This is disappointing for most of us but that is the reality. The batch of 2020 got Github water bottles and a sticker pack but we do not deserve such "swag". 
> 
> Sad indeed. But anyway thank you so much for everyone with @education for arranging this.
> 
> 
> 
> Closing this.

I'll definitely talk with the team about what we can do to make things better next year! Disappointment is not a feeling we want anyone to have receiving swag, especially during a moment to celebrate everything you've achieved over the past few years! Congrats again 💖

For graduation 2020, the general level of swag included the same card as this year and stickers. For a variety of other challenges, such as writing a blog post on DEV.to, grads could receive additional swag such as the water bottle.

**Comment by TheDynamicPunk** [comment]
Rightly said @manoj997, I'd have definitely loved to see at least a Github sticker pack in the shipment having waited for almost an year. @elisemoe  

(P.S. I've still not received the swag but have filled the replacement form. Waiting with my fingers crossed.)
