### ISSUE TITLE
replace lost or damaged shipments

### ISSUE THREAD

**Issue by A-Singh15** [education/GitHubGraduation-2021#10443]
Hi I believe the Swag got lost in the mail

**Comment by jasleen101010** [comment]
Hi! I am from India and still haven't received my swag kit. Am I missing some important info? :(

**Comment by Anonymous7code** [comment]
Same with me also didn't got any mail or any sort of indication of swag

**Comment by MichaelODeli** [comment]
Do you read this?
```
If you have not received your swag by January 31, 2022, head back to this repository and we'll open a new form to replace lost or damaged shipments.
```

**Comment by elisemoe** [comment]
If you haven't yet received your trading card, please fill out the replacement form ✨

https://github.com/education/GitHubGraduation-2021
