### ISSUE TITLE
I have filled form both time, last time and now, but didn't get any notification about it :(.

### ISSUE THREAD

**Issue by pman47** [education/GitHubGraduation-2021#10459]

**Comment by unsubstantiated-Script** [comment]
The AI is auto-rejecting valid documents....

**Comment by pman47** [comment]
Got the swags today :) thank you 😊
![IMG_20220404_162814](https://user-images.githubusercontent.com/72241422/161530811-702328ee-daa2-4f86-aa04-1ed98309cff5.jpg)
