### ISSUE TITLE
SWAG NOT RECEIVED

### ISSUE THREAD

**Issue by Anshtalwar** [education/GitHubGraduation-2021#10451]
hello team, I just wanted to let you know that I still haven't received my sway.

**Comment by pman47** [comment]
+1 😢👍

**Comment by aman339** [comment]
Even I'm too. I also did not receive it.

**Comment by Anshtalwar** [comment]
Wow no reply

**Comment by elisemoe** [comment]
If you haven't yet received your trading card, please fill out the replacement form ✨

https://github.com/education/GitHubGraduation-2021
