### ISSUE TITLE
No swag received yet on Brazil

### ISSUE THREAD

**Issue by augustoaccorsi** [education/GitHubGraduation-2021#10452]
I am from Brazil and still have not received my swag

**Comment by colodenn** [comment]
I'm from Germany and I also did not receive anything.

**Comment by Sanan4li** [comment]
Same.. No swag in pakistan. They said they'll create a form to complain but no form yet.

**Comment by xobe19** [comment]
+1, no swag yet in india.

**Comment by mitulsrv-vnsgu** [comment]
I didn't received any swag as well any email notification regarding to that. @elisemoe

**Comment by MathCarnelutt** [comment]
Also from Brazil and no swag yet

**Comment by RakshaPawar108** [comment]
No swag received in India. Waiting for the form to open up.

**Comment by thainapires** [comment]
Same here, also from Brazil

**Comment by Anonymous7code** [comment]
Same from INDIA waiting since long....

**Comment by RupomChowdhury** [comment]
I was thinking not to speak..bt i also didn't receive any kind of swag yet..😔...(I'm from Bangladesh🇧🇩)..

**Comment by elisemoe** [comment]
If you haven't yet received your trading card, please fill out the replacement form ✨

https://github.com/education/GitHubGraduation-2021
