### ISSUE TITLE
Where's the "new form to replace lost or damaged shipments"? 

### ISSUE THREAD

**Issue by Naoki95957** [education/GitHubGraduation-2021#10453]
> Keep an eye out for something fun in the mail. If you live in the United States, this means anytime from today through next week. If you live internationally, expect 3-4 weeks for shipments to arrive.
If you have not received your swag by January 31, 2022, **_head back to this repository and we'll open a new form to replace lost or damaged shipments._**

 #1175

Well I live in the states and I never saw anything in the Puget Sound of WA. I've been keeping an eye on things and was hoping to see at least the form. I'm actually moving so I'd need to update the address as well.

Hope all is going well for everyone.

**Comment by RYANSI** [comment]
I think it might take time recommend you fill the graduation 2022 as this might not be updated anytime soon

**Comment by elisemoe** [comment]
Please fill out the replacement form ✨ 

https://github.com/education/GitHubGraduation-2021
