### ISSUE TITLE
GitHub Graduation 2022 started, 2021 graduates still waiting for swags.

### ISSUE THREAD

**Issue by nitish-awasthi** [education/GitHubGraduation-2021#10470]
@elisemoe atleast provide some updates.

**Comment by RupomChowdhury** [comment]
hahahhahah.....we won't get our swag..so leave this topic now..

**Comment by retr00exe** [comment]
Yeah me too, please provide us some updates @elisemoe

**Comment by thisavijit** [comment]
GitHub graduation swag campain was really a fraud. Thank you so much @elisemoe

**Comment by elisemoe** [comment]
Hi folks 👋  graduation swag shipped twice last year. Once as the initial shipment, and again with replacement swag for anyone who hadn't received the letter by March ([see ReadMe](https://github.com/education/GitHubGraduation-2021)). We work within the limitations of available shipping services and customs, and know many of you did not receive your letters -- which sucks! 

If you never received your letter last year and would like to [participate in this year's event](https://github.com/education/GitHubGraduation-2022), we can manually review your Pull Request. Please [post a link here](https://github.com/education/GitHubGraduation-2022/issues/4290) once you've completed your PR and we will take a look. Those in the first 7,500 will receive the 2022 trading cards.

**Comment by RupomChowdhury** [comment]
@elisemoe [PR Link](https://github.com/education/GitHubGraduation-2022/pull/5276)
