### ISSUE TITLE
Create Kaafivikrant.md

### ISSUE THREAD

**Issue by kaafivikrant** [education/GitHubGraduation-2021#1740]
Application to the Class of 2021🎓
This pull request template helps you complete an application to the Class of 2021. Use the checklist below to verify you have followed the instructions correctly.

Checklist ✅
[ ✅] I have read the instructions on the README file before submitting my application.
[ ✅] I made my submission by creating a folder on the _data folder and followed the naming convention mentioned in the instructions (<username>) and markdown file.
[ ✅] I have submitted a swag shipping form.
[ ✅] I have used the Markdown file template to add my information to the Year Book.
[ ✅] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
[ ✅] I understand I should not tag or add a reviewer to this Pull Request.
[✅ ] I have added the event to my Calendar.

**Comment by harshita2216** [comment]
Hey, you need to create a pull request, and not an issue. @kaafivikrant

**Comment by SethuSenthil** [comment]
BTW this is not how you do it, you open a [pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) not an issue.

**Comment by kaafivikrant** [comment]
You just have to create a folder with your username and a file with the text they provided.. 
and create a pull.

Just wait till the grade github action is done! @harshita2216
