### ISSUE TITLE
_data/karan2762002.md

### ISSUE THREAD

**Issue by karan2762002** [education/GitHubGraduation-2021#1822]
please add my profile for GitHub graduation 2021  username- karan2762002

**Comment by karan2762002** [comment]
#996

**Comment by ayan-biswas0412** [comment]
I think there is no need to open a separate issue for that @karan2762002

**Comment by karan2762002** [comment]
choose my profile for github graduation program

**Comment by ayan-biswas0412** [comment]
> choose my profile for github graduation program

Github Officials will merge your PR if your PR successfully passes through all the checks , please wait till then

**Comment by karan2762002** [comment]
sir how to apply exactly tell me please

**Comment by ayan-biswas0412** [comment]
> sir how to apply exactly tell me please
> […](#)

just submit the PR as said in Readme and wait for the approval

**Comment by elisemoe** [comment]
We are reviewing pull requests in the order they are received 💖  It may take some time as we are a small team! But we will review and merge your pull request if it meet the event Code of Conduct.

**Comment by karan2762002** [comment]
> We are reviewing pull requests in the order they are received 💖 It may take some time as we are a small team! But we will review and merge your pull request if it meet the event Code of Conduct.

thanks a lot
