### ISSUE TITLE
Getting error while submitting pull request

### ISSUE THREAD

**Issue by amansuryawanshi** [education/GitHubGraduation-2021#2118]
Every thing is right but stil getting error

**Comment by tlarrain** [comment]
Fork the repository and create the Pull Request from there, not directly on this repo

**Comment by harshita2216** [comment]
@amansuryawanshi What error are you facing?

**Comment by Amrita0054** [comment]
Hi @amansuryawanshi.  Make sure you follow the steps correctly:
* Fork the repo you want to submit PR
* Commit and push changes to your Repo and NOT the *ORIGINAL REPO OF ANOTHER PERSON WHOM YOU WANT TO CONTRIBUTE*
* Trying to Submit the PR

**Comment by harshita2216** [comment]
@amansuryawanshi After forking, you should clone your forked repository.

**Comment by amansuryawanshi** [comment]
I got and ready to merge label is it done or do I need to do anything more

**Comment by agarwalBinay18** [comment]
why it is showing "You need to agree to our COC pretty please!". I have ticked all checkboxes

**Comment by nilsonsales** [comment]
> @amansuryawanshi After forking, you should clone your forked repository.

You can add the new file directly from GitHub website though.

**Comment by harshita2216** [comment]
> > @amansuryawanshi After forking, you should clone your forked repository.
> 
> You can add the new file directly from GitHub website though.

I know, I feel he did it by cloning it. Hence, the error. :)
