### ISSUE TITLE
Student Developer Pack check failing

### ISSUE THREAD

**Issue by johnnyapol** [education/GitHubGraduation-2021#3016]
Hello,

I've tried to apply but I keep getting rejected by the SDP check. My PR is here https://github.com/education/GitHubGraduation-2021/pull/1613

My student developer pack information is current, I even re-applied today after it first started happening and was auto-approved.

Thank you for your help.

**Comment by SmailBarkouch** [comment]
I have the same problem. I re-applied today and I don't think I'm going to get auto approved.

**Comment by shreyeh** [comment]
Make sure y'all are using your school emails, that might be an issue.

**Comment by SmailBarkouch** [comment]
I have a school email but I didn't sign up with it since it can't receive emails from stuff not from the school, and they accepted my personal so I am confused. @jonnyapol you got approved, gj bro.

**Comment by SmailBarkouch** [comment]
This is mine: https://github.com/education/GitHubGraduation-2021/pull/4053

**Comment by shreyeh** [comment]
It's not running the checks on your new commit, that's probably why you haven't been reviewed yet. Maybe, it only runs it on the first commit?

**Comment by SmailBarkouch** [comment]
Even so, all I changed was my institution name and it was fine already.

**Comment by Devansh2005** [comment]
I don't think so. For me my personal email worked well for the approval.

**Comment by karthi-002** [comment]
i have submitted my student id for github student developer pack ,but it is rejecting continously , please verify my certificate and approve
