### ISSUE TITLE
I got and ready to merge label is it done or do I need to do anything more

### ISSUE THREAD

**Issue by amansuryawanshi** [education/GitHubGraduation-2021#3026]
I got and ready to merge label is it done or do I need to do anything more

**Comment by harshita2216** [comment]
Yes, it is done. They might merge it when they are done checking other eligibility criteria.

**Comment by hardikmaks17** [comment]
thanks

**Comment by easthobb** [comment]
i was wanna know this too. thanks

**Comment by omkarkd** [comment]
Hey guyz need your help 
Uh Oh! I've found some issues with where you have created your files!
Please ensure all changes are contained within the _data/omkarkd/ directory. Invalid file paths:

.github/PULL_REQUEST_TEMPLATE.md
Please take another look at your markdown file, there are errors:
undefined

You need to agree to our COC pretty please!


got all these errors can any one help me fix it .
I  have already filled the form

**Comment by Devansh2005** [comment]
@omkarkd, you have created a file in a wrong path .Bot uncle was not able to find the correct files and folder in _data folder.

**Comment by elisemoe** [comment]
Working hard to get through all of your pull requests! 💖

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
