### ISSUE TITLE
Getting grades Expected — Waiting for status to be reported

### ISSUE THREAD

**Issue by mjglass** [education/GitHubGraduation-2021#3127]
Hello I have a pull request with the above message. I can not figure out what I am missing as I filled out the shipping form and I followed the readme instructions for creating my folder and md file.

**Comment by JuanGidoni** [comment]
Me to. Already done all the instructions and keep saying that I didnt send the form and accepted COC 😢

**Comment by mjglass** [comment]
Mine worked now. Make sure you closed the old pull request and did a new one after filling out the form that worked for me.

**Comment by JuanGidoni** [comment]
> Mine worked now. Make sure you closed the old pull request and did a new one after filling out the form that worked for me.

I think that isn't the best way to do that. For others that maybe had this issue, try to recheck or wait, do not create another PR.

**Comment by nabanita-sarkar** [comment]
> > Hello I have a pull request with the above message. I can not figure out what I am missing as I filled out the shipping form and I followed the readme instructions for creating my folder and md file.
> 
> You just need to wait. And keep trying to recheck. In the part of "Reviewers" you can ask for a new check to the bot.

Can you please share how to ask for a new check?

**Comment by nabanita-sarkar** [comment]
Thanks

**Comment by nikitaodnorob** [comment]
Hello! How long the recheck will take?

**Comment by nilsonsales** [comment]
> > > > Hello I have a pull request with the above message. I can not figure out what I am missing as I filled out the shipping form and I followed the readme instructions for creating my folder and md file.
> > > 
> > > 
> > > You just need to wait. And keep trying to recheck. In the part of "Reviewers" you can ask for a new check to the bot.
> > 
> > 
> > Can you please share how to ask for a new check?
> 
> Of course. Here:
> 
> ![How to ask for a recheck](https://camo.githubusercontent.com/7b028484e1781f143b292fca441782f15477cf759cac8dd72ef841fc8a2d8f72/68747470733a2f2f692e6779617a6f2e636f6d2f30343935323337646139626435376130376265383433366162326131626337632e706e67)
> 
> I hope I've helped

Mine says "no reviewers", but it says all checks have passed...

**Comment by JuanGidoni** [comment]
> > > > > Hello I have a pull request with the above message. I can not figure out what I am missing as I filled out the shipping form and I followed the readme instructions for creating my folder and md file.
> > > > 
> > > > 
> > > > You just need to wait. And keep trying to recheck. In the part of "Reviewers" you can ask for a new check to the bot.
> > > 
> > > 
> > > Can you please share how to ask for a new check?
> > 
> > 
> > Of course. Here:
> > ![How to ask for a recheck](https://camo.githubusercontent.com/7b028484e1781f143b292fca441782f15477cf759cac8dd72ef841fc8a2d8f72/68747470733a2f2f692e6779617a6f2e636f6d2f30343935323337646139626435376130376265383433366162326131626337632e706e67)
> > I hope I've helped
> 
> Mine says "no reviewers", but it says all checks have passed...

Maybe because you closed it. Create a new one.

**Comment by katelyn98** [comment]
If you close your pull request and open a new one it will go through. My pull request was originally in the 3000s as well but I had errors. I fixed the errors but it still wouldn't say it was ready to merge. So I closed the pull request, opened a new one, and it went through review right away and is marked as ready to merge now. Try that!

**Comment by nilsonsales** [comment]
> If you close your pull request and open a new one it will go through. My pull request was originally in the 3000s as well but I had errors. I fixed the errors but it still wouldn't say it was ready to merge. So I closed the pull request, opened a new one, and it went through review right away and is marked as ready to merge now. Try that!

I created a new pull request and it was accepted right away. Thank you!

**Comment by elisemoe** [comment]
Thank you all for helping troubleshoot! Looks like your PR has the ready to merge label and will be reviewed shortly. 💖
