### ISSUE TITLE
My PR is stuck here, do I need to do anything else?

### ISSUE THREAD

**Issue by bhatvikrant** [education/GitHubGraduation-2021#3160]
<img width="941" alt="Screenshot 2021-05-13 at 12 24 28 AM" src="https://user-images.githubusercontent.com/50735025/118029221-952f7300-b381-11eb-9a61-00efe5225734.png">

**Comment by harshita2216** [comment]
No. It's already approved.

**Comment by nabanita-sarkar** [comment]
> No. It's already approved.

So after that one can close the PR ?
