### ISSUE TITLE
The requested URL returned error: 403

### ISSUE THREAD

**Issue by iam-sachinverma** [education/GitHubGraduation-2021#355]
remote: Permission to education/GitHubGraduation-2021.git denied to USERNAME
![Capture](https://user-images.githubusercontent.com/83693262/117937107-3fc47900-b323-11eb-980a-5888887cbd28.PNG)

**Comment by ME-ON1** [comment]
you can not directly push to upstream. push to your forked repo and then make a PR.

**Comment by slayer321** [comment]
@iam-sachinverma  you need to create a branch and then PR it 
You cannot directly push to main

**Comment by Safnaj** [comment]
@iam-sachinverma 

1. Fork the Repo
2. Add your details
3. Send a Pull Request (PR) to main Repo

**Comment by iam-sachinverma** [comment]
thankuu everyone, it's work for me .....

**Comment by iam-sachinverma** [comment]
thankuu everyone, it's work for me .....
