### ISSUE TITLE
sujeeth-shetty

### ISSUE THREAD

**Issue by Sujeeth-Shetty** [education/GitHubGraduation-2021#3575]
---
name: Sujeeth Shetty 
institution: University of Texas at Dallas 
quote: contribute to open source  
github_user: sujeeth-shetty
---

**Comment by harshita2216** [comment]
@Sujeeth-Shetty You need to create a pull request.

**Comment by Sujeeth-Shetty** [comment]
Choose different branches or forks above to discuss and review changes. Learn about pull requests 
I am getting this error. any idea?
