### ISSUE TITLE
Waiting recheck too long

### ISSUE THREAD

**Issue by nikitaodnorob** [education/GitHubGraduation-2021#4514]
Hello! I made a pull request #2514 and the bot sent me remark about shipping form. But I had filled this form before.

I requested a new review and then fixed a typo (it was almost hour ago). And I'm still waiting review.

My second commit has passed check, but the check got error...
```
Request quota exhausted for request GET /repos/{owner}/{repo}/contents/{path}
(node:2582) UnhandledPromiseRejectionWarning: ReferenceError: feedpack is not defined
    at /home/runner/work/GitHubGraduation-2021/GitHubGraduation-2021/.github/workflows/src/index.js:81:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2582) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2582) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can you help me please? Seems that the bot skipped my PR

**Comment by elisemoe** [comment]
Hello 👋 Please try resubmitting the form and ensure you use the same capitalization when filling out your GitHub username as you use in the markdown file. We're working to resolve this but it's doing an exact compare at the moment :)

**Comment by nikitaodnorob** [comment]
@elisemoe thank you for answer! I've resubmitted just now. The capitalization is the same.

But the check is expected more than hour. I can't restart the job and can't make new request for review
![image](https://user-images.githubusercontent.com/24944339/118040075-c5731380-b379-11eb-9e3b-35e875ecd1f0.png)

**Comment by Hypro999** [comment]
I've been noticing the same thing. After removing some potentially special characters from my quote I pushed a new commit to my PR and waited overnight for the CI to run. But it hasn't. Not sure if I should open a new issue for this or not...

**Comment by elisemoe** [comment]
> @elisemoe thank you for answer! I've resubmitted just now. The capitalization is the same.
> 
> But the check is expected more than hour. I can't restart the job and can't make new request for review
> ![image](https://user-images.githubusercontent.com/24944339/118040075-c5731380-b379-11eb-9e3b-35e875ecd1f0.png)

Looks like you're all set! We'll be by in the next day to merge your PR.

**Comment by nikitaodnorob** [comment]
@elisemoe I had closed this PR and opened new one, it is ok. Thank you!)

**Comment by elisemoe** [comment]
We will merge this PR :) https://github.com/education/GitHubGraduation-2021/pull/8018

Nothing you need to do now but wait!
