### ISSUE TITLE
Not reviewed 

### ISSUE THREAD

**Issue by joeljsv** [education/GitHubGraduation-2021#4530]
my PR has been ready to merge but the bot doest reviewed.
#4012

**Comment by katelyn98** [comment]
If you close your pull request and open a new one it will go through. My pull request was originally in the 3000s as well but I had errors. I fixed the errors but it still wouldn't say it was ready to merge. So I closed the pull request, opened a new one, and it went through review right away and is marked as ready to merge now. Try that!

**Comment by elisemoe** [comment]
Thank you both for helping troubleshoot! Looks like your PR has the ready to merge label and will be reviewed shortly. 💖
