### ISSUE TITLE
review failed #4459, please help me out

### ISSUE THREAD

**Issue by ParvezAhmed111** [education/GitHubGraduation-2021#4645]
please help me with my pull request #4459
i am not getting what this error is

**Comment by vp1099** [comment]
Please provide more information

**Comment by ParvezAhmed111** [comment]
![image](https://user-images.githubusercontent.com/46757345/118037146-17706500-b38b-11eb-8dd1-cfb51255b077.png)

**Comment by ParvezAhmed111** [comment]
![image](https://user-images.githubusercontent.com/46757345/118037281-438be600-b38b-11eb-9d44-a4879ca37baa.png)

![image](https://user-images.githubusercontent.com/46757345/118037372-60281e00-b38b-11eb-9153-0b207ee2cc77.png)

**Comment by ParvezAhmed111** [comment]
What should i do? @vp1099

**Comment by vp1099** [comment]
Please fill the form with all the correct details without any mistakes! And request the bot for the review again

**Comment by vp1099** [comment]
If this does not work try to create a fresh pull request

**Comment by ParvezAhmed111** [comment]
> Please fill the form with all the correct details without any mistakes! And request the bot for the review again

Which form??

**Comment by vp1099** [comment]
https://airtable.com/shrM5IigBuRFaj33H

**Comment by DarshGupta1910** [comment]
@ParvezAhmed111  your pull request accepted?

**Comment by ParvezAhmed111** [comment]
> @ParvezAhmed111 your pull request accepted?

Not yet brother

**Comment by afsara-ben** [comment]
i have filled out the form correctly but still getting this error

**Comment by ParvezAhmed111** [comment]
![image](https://user-images.githubusercontent.com/46757345/118039484-06752300-b38e-11eb-830d-dc4bf905bd2b.png)

@vp1099 how to merge pull request?

**Comment by vp1099** [comment]
It's done now , now the owners will merge your pull request, you don't have to do anything

**Comment by ParvezAhmed111** [comment]
how much time it takes generally?

**Comment by vp1099** [comment]
Also your pull request is #4850 so you just made it under 5000 
So congratulations for that ! 

The merging process will take place serially and currently only 700 PR's have been merged 
So your patience is requested 
It might take 10-12 or even more or even less

**Comment by ParvezAhmed111** [comment]
> Also your pull request is #4850 so you just made it under 5000
> So congratulations for that !
> 
> The merging process will take place serially and currently only 700 PR's have been merged
> So your patience is requested
> It might take 10-12 or even more or even less

All thanks to you brother!!
Thanks for the help
