### ISSUE TITLE
Bot seems to be skipping over PRs

### ISSUE THREAD

**Issue by notjasonl** [education/GitHubGraduation-2021#4646]
Made PR #1075 a few hours ago and it was left entirely unreviewed, then closed, deleted fork and tried again with #4359 only to have the bot ignore it again

**Comment by luis-valdez** [comment]
same problem here

**Comment by saurabhkumar1432** [comment]
They are at 600 for now

**Comment by GabrielaBezerra** [comment]
Same thing, some PRs that had just been created are already marked ready for merge, and mine which was created one hour ago still hasn’t been reviewed yet

**Comment by adamesalles** [comment]
I've made #1652 and he asked for reducing the quote. I did it there's 2 hours and nothing of beeing accepted.

**Comment by katelyn98** [comment]
If you close your pull request and open a new one it will go through. My pull request was originally in the 3000s as well but I had errors. I fixed the errors but it still wouldn't say it was ready to merge. So I closed the pull request, opened a new one, and it went through review right away and is marked as ready to merge now. Try that!

**Comment by adamesalles** [comment]
I did something like what @katelyn98 said. It was automatic.

**Comment by elisemoe** [comment]
> Made PR #1075 a few hours ago and it was left entirely unreviewed, then closed, deleted fork and tried again with #4359 only to have the bot ignore it again

I've manually requested the bot review your pull request. Thank you all for helping troubleshoot 💖
