### ISSUE TITLE
It's saying I am missing all my attributes even though it is there in the markdown format...

### ISSUE THREAD

**Issue by PotentialError** [education/GitHubGraduation-2021#4813]
Here's how it looks:
![image](https://user-images.githubusercontent.com/61915029/118037846-617e2a00-b33c-11eb-916e-1de41b99fba6.png)

**Comment by Siraj-Qazi** [comment]
I think it said _don't use special characters in the template above._
Maybe your colon in the _quote_ is causing the issue.

**Comment by PotentialError** [comment]
Yup looks like colons cause problems with markdown! Thanks @Siraj-Qazi

**Comment by Siraj-Qazi** [comment]
Np :)
