### ISSUE TITLE
Can't tell if my PR is to the right repository.

### ISSUE THREAD

**Issue by toadius2** [education/GitHubGraduation-2021#4829]
I committed my code to the repository i forked to my own account and pushed it there and submitted my pull request there, but I don't know if that was correct if I was just doing that to my own local version of the repo. Someone please help me figure out how to commit it to the actual repo to submit my PR because it is not clear at all to me. I tried doing it through the repo i cloned directly too but i just get a permission denied error.

**Comment by saurabhkumar1432** [comment]
Do it online directly

**Comment by toadius2** [comment]
How? I don't have permission to add a file directly

**Comment by Sanan4li** [comment]
Here are the steps I followed.
1. forked the repo
2. cloned it on my computer from my account
3. created a new brank
4. added the folder and .md file
5. committed those changes to the new branch
6. checked the account to request a new pull request.

**Comment by toadius2** [comment]
So do you request that PR in your OWN forked repo then?

**Comment by Sanan4li** [comment]
> So do you request that PR in your OWN forked repo then?

No it will be automatically requested to main repo..

**Comment by elisemoe** [comment]
> I committed my code to the repository i forked to my own account and pushed it there and submitted my pull request there, but I don't know if that was correct if I was just doing that to my own local version of the repo. Someone please help me figure out how to commit it to the actual repo to submit my PR because it is not clear at all to me. I tried doing it through the repo i cloned directly too but i just get a permission denied error.

I see your PR is created to the correct repository and has the label "ready to merge". We'll be along in the next for the manual review and to merge your PR 💖
