### ISSUE TITLE
Agree to COC

### ISSUE THREAD

**Issue by lchoicer55** [education/GitHubGraduation-2021#4839]
I'm getting the error that I need to agree to the COC.

I thought this error was regarding the checklist but I already have that completed. Can someone direct me to what this means?

https://github.com/education/GitHubGraduation-2021/pull/4735

**Comment by harshita2216** [comment]
You need to fill the shipping form. @lchoicer55

**Comment by lchoicer55** [comment]
> You need to fill the shipping form. @lchoicer55
> In the shipping form, we have a checkbox for agreeing to the CoC.

Thanks! Turns out I had a small capitalization error in my username when I filled out the form
