### ISSUE TITLE
Check failed - failure: getting grades but why

### ISSUE THREAD

**Issue by afsara-ben** [education/GitHubGraduation-2021#4877]
![image](https://user-images.githubusercontent.com/44926095/118038207-a59b1a00-b390-11eb-9c99-009b8bb19b34.png)

**Comment by saurabhkumar1432** [comment]
Send the error

**Comment by filipejesse** [comment]
![image](https://user-images.githubusercontent.com/26888521/118038924-1e28b900-b346-11eb-9ef4-7fd44bf2c1e0.png)
Seems like you don't have the development pack bro

**Comment by Sanan4li** [comment]
You should check email.. there will be explanation.. if you don't have valid student pack it will be mentioned in the email

**Comment by ME-ON1** [comment]
Do you have a student developer pack applied for 2021 ending batch ??!

**Comment by elisemoe** [comment]
It looks like the bot hasn't ran on your pull request yet @afsara-ben. I've manually requested a review.

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
