### ISSUE TITLE
Bug Report: Include full first name for passing bot checks

### ISSUE THREAD

**Issue by PSSF23** [education/GitHubGraduation-2021#4976]
I went through the approved PRs and found the authors' names to be at least **full first name**. After updating my PR #1430  with full name, the checks finally passed.

According to the template, nicknames should be accepted without issues. I believe the checking algorithms currently focus on name searches to make sure the person agreed to the COC. Perhaps switching the check to GitHub username should resolve this issue.

**Comment by Sanan4li** [comment]
glad to hear it.. please close the issue.

**Comment by PSSF23** [comment]
@Sanan4li Not until the problem is solved on GitHub's end.

Also a reminder for people with approved PRs: Don't close them XD. It's just hilarious how many people closed the PRs without merging.

**Comment by PSSF23** [comment]
@renz45 Sorry for bothering you as I found no guidelines for reporting bugs. I believe this is an issue related to @GitHub-Education-bot.

**Comment by juanpflores** [comment]
Found both form submissions. The username was not entered correctly the first time but it was corrected on a second submission.

**Comment by PSSF23** [comment]
@juanpflores Thank you so much! Really appreciate the insight!
