### ISSUE TITLE
Susmita692.md

### ISSUE THREAD

**Issue by Susmita692** [education/GitHubGraduation-2021#5011]
Not being able to pull requests

**Comment by nikitaodnorob** [comment]
you should fork this repository, push commits to your repo and then create pull request from the fork

**Comment by Sanan4li** [comment]
please share some more details..

**Comment by ME-ON1** [comment]
Hi looked into  your PR. you have not made a dir of your name or markdown of your username and you haven't filled the shipment form yet. Look into the error message

**Comment by elisemoe** [comment]
Hi @Susmita692 👋 It looks like you have 8 open pull requests. Can you please close the ones you are not working on or let me know which you would like to keep and I can close the others for you?

**Comment by elisemoe** [comment]
Closing this Issue. You are welcome to tag me in a pull request for help with the instructions if you'd like to continue working our your yearbook submission.
