### ISSUE TITLE
I'm not sure if I did it right.

### ISSUE THREAD

**Issue by djoshua21** [education/GitHubGraduation-2021#5129]
This was the last thing I got and wanted to know if this is correct.

![image](https://user-images.githubusercontent.com/67048778/118040145-7fb24d00-b371-11eb-8ec6-47dd25ef5fcc.png)

**Comment by ParvezAhmed111** [comment]
i guess it got merged

**Comment by djoshua21** [comment]
so is it right then?

I'll just show this stuff just to be sure.
![image](https://user-images.githubusercontent.com/67048778/118040642-1848cd00-b372-11eb-9756-e3aab97ed53a.png)

**Comment by ParvezAhmed111** [comment]
it got merged

**Comment by ParvezAhmed111** [comment]
dont close this issue
let others confirm it too

**Comment by elisemoe** [comment]
👋  @djoshua21  can you please post a link to your pull request and I'll confirm?

**Comment by djoshua21** [comment]
https://github.com/djoshua21/GitHubGraduation-2021/pull/1

**Comment by ME-ON1** [comment]
Hi you have merge this PR into your forked version. Not in the upstream (main repo ) make a PR there

**Comment by djoshua21** [comment]
I managed to get it right after all but the only reason I got it wrong was because it said to fork the repository in the instruction and that just threw me off completely.

**Comment by elisemoe** [comment]
Hi @djoshua21 👋 It looks like the PR you've created is on your own fork of the repository. You will need to create a PR on this repository. 

![Screen Shot 2021-05-13 at 11 58 47 AM](https://user-images.githubusercontent.com/6633808/118173652-b4122180-b3e2-11eb-9f0e-343d7484980f.png)

You can do this by clicking the "New pull request" button here - https://github.com/education/GitHubGraduation-2021/pulls

Select "compare across forks" and then select your branch in the drop down.

![Screen Shot 2021-05-13 at 12 01 13 PM](https://user-images.githubusercontent.com/6633808/118173851-f20f4580-b3e2-11eb-8cca-31402131691a.png)
