### ISSUE TITLE
Post-approval commit may have stalled the checks #4943

### ISSUE THREAD

**Issue by xanderkoo** [education/GitHubGraduation-2021#5164]
#4943

I made an edit while waiting for the PR to get approved, but I missed the timing and the commit went through after the PR was already approved. I think that extra commit might have messed up the automatic checks. Will this prevent my PR from being merged?

<img width="926" alt="Screen Shot 2021-05-12 at 1 33 08 PM" src="https://user-images.githubusercontent.com/33564284/118040598-98494580-b326-11eb-9294-744aa7a8e78b.png">

**Comment by nikitaodnorob** [comment]
I have a same problem, the check is expected more hour

**Comment by sunilgknair051** [comment]
I guess you just have to wait, there are around 4k PRs, and bots trying to push checking the prereqs...will take time. Let there be patience!

**Comment by elisemoe** [comment]
> #4943
> 
> I made an edit while waiting for the PR to get approved, but I missed the timing and the commit went through after the PR was already approved. I think that extra commit might have messed up the automatic checks. Will this prevent my PR from being merged?
> 
> <img alt="Screen Shot 2021-05-12 at 1 33 08 PM" width="926" src="https://user-images.githubusercontent.com/33564284/118040598-98494580-b326-11eb-9294-744aa7a8e78b.png">

It looks like your PR has been approved for manual review!

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁

**Comment by xanderkoo** [comment]
Gotcha, thanks so much for all you're doing!!
