### ISSUE TITLE
Violation of file/folder structure.

### ISSUE THREAD

**Issue by code-abil** [education/GitHubGraduation-2021#5167]
The below markdown file does not accompany any <user_name> parent directory. It is present directly in the _data  folder.
[Markdown File Link](https://github.com/education/GitHubGraduation-2021/blob/main/_data/crypticani.md)
@crypticani

**Comment by sunilgknair051** [comment]
yep, fork first, create a folder and then create the .md file in it.

**Comment by code-abil** [comment]
@crypticani

**Comment by elisemoe** [comment]
Thank-you both! I'll be sure to resolve this before we deploy :)
