### ISSUE TITLE
review bot not added

### ISSUE THREAD

**Issue by ojasvishaklya** [education/GitHubGraduation-2021#5176]
there's no review bot #3135

**Comment by GabrielaBezerra** [comment]
same happening with me #3180

**Comment by Lynicis** [comment]
same problem #3851

**Comment by katelyn98** [comment]
If you close your pull request and open a new one it will go through. My pull request was originally in the 3000s as well but I had errors. I fixed the errors but it still wouldn't say it was ready to merge. So I closed the pull request, opened a new one, and it went through review right away and is marked as ready to merge now. Try that!

**Comment by Lynicis** [comment]
thx for helping but was so weird issue
