### ISSUE TITLE
Cannot merge PR successfully.Please help!

### ISSUE THREAD

**Issue by mehuli12** [education/GitHubGraduation-2021#5196]
![github](https://user-images.githubusercontent.com/78132955/118040789-a2ebf500-b38f-11eb-8607-6b8caaf5e16e.JPG)

![github2](https://user-images.githubusercontent.com/78132955/118040890-c44ce100-b38f-11eb-8287-afadfde89246.JPG)

**Comment by Devansh2005** [comment]
Changes are requested from you @mehuli12 !

**Comment by mehuli12** [comment]
@Devansh2005  I did make a few changes. But the changes aren't mentioned in the last review

**Comment by Devansh2005** [comment]
I think you have deleted the whole folder @mehuli12 ! Close this PR and try to make a new PR , ensuring that the changes are now correct.

**Comment by mehuli12** [comment]
Cannot create a new one now

**Comment by avinsit123** [comment]
Open your previous PR and re-request a review. I had the exact same problem was solved by re-requesting a review.

**Comment by mehuli12** [comment]
Hi @avinsit123
I managed to send a PR successfully.
I didn’t create 2 files inside ‘data’, hence such problem.
Thanks!
