### ISSUE TITLE
Can not merge PR request 

### ISSUE THREAD

**Issue by poojaagrawal134** [education/GitHubGraduation-2021#5257]
Please look into!

**Comment by ParvezAhmed111** [comment]
please provide more details

**Comment by poojaagrawal134** [comment]
I dont know if i am going write or not. My merge request is done or not please help me

**Comment by poojaagrawal134** [comment]
![Uploading 81D62677-FCA6-4852-A84F-2DBF70394349.png…]()

**Comment by ParvezAhmed111** [comment]
reupload the pic

**Comment by poojaagrawal134** [comment]
![D3B02107-BA13-400D-ADBC-89B1787FDAD8](https://user-images.githubusercontent.com/51293336/118042701-05de8b80-b392-11eb-8e44-0b8cfc9b4b3c.png)

**Comment by ParvezAhmed111** [comment]
you have commit files?

**Comment by poojaagrawal134** [comment]
1)Fork the repo
2)make changes in pull_rqst demo template the propose pull to a new branch 
3)Merge pull reqst

**Comment by Devansh2005** [comment]
@poojaagrawal134 You have not made a PR yet.

**Comment by poojaagrawal134** [comment]
Please let me know the correct steps to do this i am not able to again fork the repo

**Comment by ParvezAhmed111** [comment]
follow these steps.

1. fork the repo
2. make a folder and add files - 1. your pic   2. your graduation details  (check other folders and see how others did)
3. now fill this form first:  https://airtable.com/shrM5IigBuRFaj33H
4. after that create a pull request

**Comment by Devansh2005** [comment]
The PR was made but all the checks were wrong. You have edited .gitignore file also.

**Comment by ParvezAhmed111** [comment]
> follow these steps.
> 
> 1. fork the repo
> 2. make a folder and add files - 1. your pic   2. your graduation details  (check other folders and see how others did)
> 3. now fill this form first:  https://airtable.com/shrM5IigBuRFaj33H
> 4. after that create a pull request

no need to fork again

just open the _data folder and add files (like how others added)

**Comment by ParvezAhmed111** [comment]
or delete the repo and fork again

**Comment by poojaagrawal134** [comment]
Not able to delete the repo

**Comment by poojaagrawal134** [comment]
> > follow these steps.
> > 
> > 1. fork the repo
> > 2. make a folder and add files - 1. your pic   2. your graduation details  (check other folders and see how others did)
> > 3. now fill this form first:  https://airtable.com/shrM5IigBuRFaj33H
> > 4. after that create a pull request
> 
> no need to fork again
> 
> just open the _data folder and add files (like how others added)
 
There is folder of others but i am not able to create folder there

**Comment by ParvezAhmed111** [comment]
create a folder on your desktop, add you pic there
then open _data folder, drag and drop the folder from your system to the _data folder
after that click on commit changed button at the bottom

**Comment by Devansh2005** [comment]
@ParvezAhmed111 , I think these are not the right steps, the bot is checking for the keywords "name", "institution", "github_user", "quote". A picture is to be added ?

**Comment by techpkd123** [comment]
do we need to merge also or merging the PR will be done by people from github???

**Comment by ParvezAhmed111** [comment]
yaa, i am suggesting the simple steps
my PR got ready to merge label

**Comment by techpkd123** [comment]
ok so now we need not do anything right after getting the ready to merge label?

**Comment by Devansh2005** [comment]
No more to do from our side @techpkd123. We'll be notified if bot approved us. (Merging our PR)

**Comment by poojaagrawal134** [comment]
I forked the repo again now i just have to add a file in _data folder right?

**Comment by poojaagrawal134** [comment]
Is there any manual way to do it? I am not using desktop

**Comment by ParvezAhmed111** [comment]
> @ParvezAhmed111 , I think these are not the right steps, the bot is checking for the keywords "name", "institution", "github_user", "quote". A picture is to be added ?

after doing that open your folder from _data folder, 
Click add file -> create new files
and do in the same way as i did (follow the pic)
![image](https://user-images.githubusercontent.com/46757345/118044558-6ff83000-b394-11eb-9465-fd378b7e9bdb.png)

**Comment by ParvezAhmed111** [comment]
> Is there any manual way to do it? I am not using desktop

yes

**Comment by ParvezAhmed111** [comment]
> Is there any manual way to do it? I am not using desktop

open _data-> create new files-> "folder_name" / -> file_name.md

---
name: 
institution: 
quote: 
github_user: 
---

copy paste it and fill your details, then commit changes

**Comment by ParvezAhmed111** [comment]
![image](https://user-images.githubusercontent.com/46757345/118045317-63c0a280-b395-11eb-91c3-055d7376a463.png)

**Comment by ParvezAhmed111** [comment]
no,  Commit directly to the main branch.

**Comment by poojaagrawal134** [comment]
![32893227-8F4F-4553-87F4-57410A99489E](https://user-images.githubusercontent.com/51293336/118045823-1133b600-b396-11eb-8bd8-30bc647614e4.png) 
Done now?

**Comment by poojaagrawal134** [comment]
I have filled the form.how to create pull request

**Comment by ParvezAhmed111** [comment]
![image](https://user-images.githubusercontent.com/46757345/118046171-95863900-b396-11eb-9648-a4b6bee21258.png)

come to this page
click Pull requests

**Comment by ParvezAhmed111** [comment]
![image](https://user-images.githubusercontent.com/46757345/118046256-b2bb0780-b396-11eb-87eb-9aa13ec90142.png)

then new pull request

**Comment by ParvezAhmed111** [comment]
then create pull request

**Comment by ParvezAhmed111** [comment]
![image](https://user-images.githubusercontent.com/46757345/118046423-f3b31c00-b396-11eb-8a31-b1a7fe5ec6b2.png)

give a title like "ParvezAhmed111 application"

then at the bottom, create pull request

**Comment by ParvezAhmed111** [comment]
do check the boxes after creating pull request

**Comment by poojaagrawal134** [comment]
![2AC67555-5A60-4481-9A1C-3F4252562C60](https://user-images.githubusercontent.com/51293336/118046994-bf8c2b00-b397-11eb-959d-f94e4a140bbe.png)

Can i use ✅ when creating pull reqst like in ss

**Comment by ParvezAhmed111** [comment]
no after creating pull request you can check the boxes

**Comment by poojaagrawal134** [comment]
![6B59AAFB-0593-4C64-9A05-D054A6C13F05](https://user-images.githubusercontent.com/51293336/118047495-77213d00-b398-11eb-8982-4d50587d6ddf.png)
![689C7DDF-5699-4F94-B924-3CDDF3C4A468](https://user-images.githubusercontent.com/51293336/118047506-7be5f100-b398-11eb-9399-cccef9896fad.png)
![3DC4F4C4-C782-49FD-85A6-1FF73899CD91](https://user-images.githubusercontent.com/51293336/118047510-7d171e00-b398-11eb-9010-dfb84e1eba42.png)
![988D7E6F-20D9-4D35-97A9-924E84D51D79](https://user-images.githubusercontent.com/51293336/118047512-7dafb480-b398-11eb-93f6-f7bfd1f47c01.png)

**Comment by ParvezAhmed111** [comment]
you have enterd wrong path

**Comment by poojaagrawal134** [comment]
How to correct it now

**Comment by ParvezAhmed111** [comment]
i dont know how to rename a folder with phone

its better delete that folder and upload the files again

**Comment by ParvezAhmed111** [comment]
poojaagarwal134

keep this as folder name (all are in small caps)
poojaagarwal134.md (file)
poojaagarwal134.jpeg (pic)

keep same name

**Comment by ParvezAhmed111** [comment]
after that close this pull request 
and create a new pull request again

**Comment by poojaagrawal134** [comment]
![A3AF994D-AED5-456A-A69C-5C9717E3FD6D](https://user-images.githubusercontent.com/51293336/118049137-ec8e0d00-b39a-11eb-88b8-2e74350fbf60.png)
Still getting this

**Comment by poojaagrawal134** [comment]
Yes approve now can i close pull reqst now?

**Comment by poojaagrawal134** [comment]
![FA5835B5-7525-4C12-9F0A-F4AC8F39B7E8](https://user-images.githubusercontent.com/51293336/118049579-8eadf500-b39b-11eb-8554-21abbbeeb2a9.png)

**Comment by poojaagrawal134** [comment]
> after that close this pull request
> and create a new pull request again

Please guide me in merging also

**Comment by Devansh2005** [comment]
@poojaagrawal134 See yr , you have not created the file where it has to be and also another folder was disturbed. You can read the guidelines once more. There is no such formality where you need to upload your picture.
The merging will not be done until you will get a "ready to merge" label.

If you want a help, I will let you know how this is working.

**Comment by poojaagrawal134** [comment]
> @poojaagrawal134 See yr , you have not created the file where it has to be and also another folder was disturbed. You can read the guidelines once more. There is no such formality where you need to upload your picture.
> The merging will not be done until you will get a "ready to merge" label.
> 
> If you want a help, I will let you know how this is working.

I got  this label

**Comment by poojaagrawal134** [comment]
> after that close this pull request
> and create a new pull request again

I am following these steps

**Comment by poojaagrawal134** [comment]
> > @poojaagrawal134 See yr , you have not created the file where it has to be and also another folder was disturbed. You can read the guidelines once more. There is no such formality where you need to upload your picture.
> > The merging will not be done until you will get a "ready to merge" label.
> > If you want a help, I will let you know how this is working.
> 
> I got this label

Please help me with merging

**Comment by poojaagrawal134** [comment]
@Devansh2005 please help

**Comment by Devansh2005** [comment]
#5711, If you are talking about this PR, you didn't get a label.

**Comment by poojaagrawal134** [comment]
![D75C9D2E-C37C-482D-BEEA-D5E27CF62FB8](https://user-images.githubusercontent.com/51293336/118051311-64116b80-b39e-11eb-80d5-c8838c67b214.png)

**Comment by Devansh2005** [comment]
Why yo closed it ?

**Comment by ParvezAhmed111** [comment]
#5800, great it's ready to merge now

**Comment by poojaagrawal134** [comment]
> Why you closed it ?

I don’t know i am following steps suggested by @ParvezAhmed111

**Comment by ParvezAhmed111** [comment]
@poojaagrawal134 congrats💐

**Comment by poojaagrawal134** [comment]
> #5800, great it's ready to merge now

Help me to complete it please

**Comment by ParvezAhmed111** [comment]
You are done now, 
GitHub graduation will merge it from their side after some days

**Comment by poojaagrawal134** [comment]
> @poojaagrawal134 congrats💐

You asked me to close it before merge🤔

**Comment by ParvezAhmed111** [comment]
You can close this issue now.

**Comment by poojaagrawal134** [comment]
> You are done now,
> GitHub graduation will merge it from their side after some days

Do i need to close it or should i reopen this pull request again?

**Comment by ParvezAhmed111** [comment]
Don't close the pull request,
You can check the status from the pull request section on this repository

**Comment by Devansh2005** [comment]
Reopen the PR ... And close this issue

**Comment by ParvezAhmed111** [comment]
![image](https://user-images.githubusercontent.com/46757345/118046171-95863900-b396-11eb-9648-a4b6bee21258.png)

From here

**Comment by ParvezAhmed111** [comment]
Sorry from your profile

**Comment by poojaagrawal134** [comment]
Thank you so muck @ParvezAhmed111 @Devansh2005

**Comment by ParvezAhmed111** [comment]
You're welcome😊

**Comment by ParvezAhmed111** [comment]
Close this issue now

**Comment by Devansh2005** [comment]
That was really a great challenge to do it with mobile. 😁😁
