### ISSUE TITLE
Unable to apply (or revalidate?) SDP

### ISSUE THREAD

**Issue by yhling** [education/GitHubGraduation-2021#5304]
Tried going to https://education.github.com/discount_requests/student_application?utm_source=2021-06-05-GitHubGraduation but got  
  
![image](https://user-images.githubusercontent.com/9102395/118042016-1dc00a80-b3a6-11eb-8458-15fc66621b58.png)

What gives?

**Comment by Devansh2005** [comment]
@yhling , the link worked in my case. Try it going there with" https://education.github.com"

**Comment by yhling** [comment]
@Devansh2005 Same thing. As soon as I try to sign in within that subdomain it just 404'd for me. Oh wells.

**Comment by elisemoe** [comment]
Hello 👋 Were you all able to access the link to re-verify student status? I know the GitHub API was down for sometime and may have been the cause of these issues. Let me know if you are continuing to have trouble.
