### ISSUE TITLE
Not Reviewed

### ISSUE THREAD

**Issue by Pavankalyannvs** [education/GitHubGraduation-2021#5307]
My PR is ready to Merge. But Bot doesn't reviewed

**Comment by nelsonwenner** [comment]
Requested a new review? I had problems and when I asked for a new reviewer everything went well. #4880

**Comment by Ujjk29** [comment]
What is the process of requesting review from the bot?

**Comment by Pavankalyannvs** [comment]
Submit Pull Request.Bot automatically Review it..!!
