### ISSUE TITLE
Merge request Not done!

### ISSUE THREAD

**Issue by techpkd123** [education/GitHubGraduation-2021#5430]
I have been successfully submitted my work but not merged yet.

**Comment by techpkd123** [comment]
Kindly if possible someone please merge my PR as I have submitted  and PR is ready to merge and and last I would like to thanks Github for such a wonderful program.

**Comment by g-delmo** [comment]
There's more than 4,000 pull requests open 😄  so it might take them some time (hours? maybe even more) to get to yours.

**Comment by techpkd123** [comment]
okay so since I have got ready to merge now So i need not do anything right and  rest it will be merged by ones from github ?

**Comment by g-delmo** [comment]
Your PR will be merged by a member of staff once reviewed, yes. But bear in mind that there is a limit of 5,000 graduates. I am assuming your PR # was below this figure. If so, then you just have to wait.

**Comment by techpkd123** [comment]
Okay so is the review done on what basis like we just had to change the file right?

**Comment by HariAcidReign** [comment]
Yes. Adding your details is enough to get merged.

**Comment by ME-ON1** [comment]
It's FIFO. Member are taking care of the PR made before you. They will get to everyone eventually

**Comment by elisemoe** [comment]
It looks like your PR is ready to be merged and will be reviewed by a team member in the next day!

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁

**Comment by techpkd123** [comment]
Thank you for the update.Hope my PR gets merged today!!
