### ISSUE TITLE
Error: Review required?

### ISSUE THREAD

**Issue by jmoscoso1** [education/GitHubGraduation-2021#5456]
Why am i getting error "Review required
At least 1 approving review is required by reviewers with write access"

**Comment by Devansh2005** [comment]
@jmoscoso1 , the bot will be the reviewer. I see you have closed the PR.

**Comment by jmoscoso1** [comment]
how do i reopen it?

**Comment by Devansh2005** [comment]
Go to the PR , the last option will be Open this PR. 
Closing this issue will also give alike option to reopen the issue 🤠🤠
