### ISSUE TITLE
Help: Adding all of the information, but keep being told that I'm not adding attributes

### ISSUE THREAD

**Issue by cinthavong** [education/GitHubGraduation-2021#5492]
I have a few items I need you to take care of before I can merge this PR:
Please take another look at your markdown file, there are errors:
The yaml content in _data/cinthavong/cinthavong.md must contain your github username
The attribute name is required in _data/cinthavong/cinthavong.md
The attribute institution is required in _data/cinthavong/cinthavong.md
The attribute quote is required in _data/cinthavong/cinthavong.md
Feel free to re-request a review from me and I'll come back and take a look!

**Comment by Devansh2005** [comment]
Great 👌👌👌😎

**Comment by juanpflores** [comment]
Please accept the suggestions left in the code.
