### ISSUE TITLE
PR #1028 isn't merged yet (raised 4 hours ago) despite being ready to merge. 

### ISSUE THREAD

**Issue by Tiwarim386** [education/GitHubGraduation-2021#5616]
Pr number #1028 isn't merged yet despite being ready to merge. Can someone look into this please? 
Seems like bot is skipping PR's
Thanks

**Comment by adamesalles** [comment]
The same with me at #1652

**Comment by Tiwarim386** [comment]
Merging is going on sequentially I've figured out. Closing this issue
