### ISSUE TITLE
#4403 is not merged yet and required Review

### ISSUE THREAD

**Issue by sayandey425** [education/GitHubGraduation-2021#5685]
PR number #4403 isn't merged yet and Review required. Can someone look into this, please? @GitHub-Education-bot 
Thank you

**Comment by Devansh2005** [comment]
I think this is because the PR was closed for a minute. I'm not very sure.

**Comment by elisemoe** [comment]
It looks like your PR is ready to merge!

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
