### ISSUE TITLE
My PR Added myself to the family #3205 is not merged and has not got any reviews yet.

### ISSUE THREAD

**Issue by shrabanti72** [education/GitHubGraduation-2021#5846]

**Comment by katelyn98** [comment]
If you close your pull request and open a new one it will go through. My pull request was originally in the 3000s as well but I had errors. I fixed the errors but it still wouldn't say it was ready to merge. So I closed the pull request, opened a new one, and it went through review right away and is marked as ready to merge now. Try that!

**Comment by shrabanti72** [comment]
Thanks.... I did this and it is now ready to merge. But my PR is 8000+ now.

**Comment by dhruvsheth-ai** [comment]
Instead of closing, you had to re-request a review. That would do the job. You can repoen your PR and then, re-request a review.
