### ISSUE TITLE
#4608 is not merged yet and requires review

### ISSUE THREAD

**Issue by Ghamry0x2** [education/GitHubGraduation-2021#5880]
My PR  #4608 is not reviewed yet by the bot while all checks are passed.
"Review required. At least 1 approving review is required by reviewers with write access."

**Comment by nicolebzf** [comment]
did you create a branch? I can't seem to make a pull request without making a branch first, but that's not in the instructions

**Comment by Ghamry0x2** [comment]
@nicolebzf You're correct, It worked! 🎉
It's approved and all is good but it's not merged yet...

**Comment by katelyn98** [comment]
If you close your pull request and open a new one it will go through. My pull request was originally in the 3000s as well but I had errors. I fixed the errors but it still wouldn't say it was ready to merge. So I closed the pull request, opened a new one, and it went through review right away. Try that!

I did not need to create a branch either.

**Comment by elisemoe** [comment]
> My PR #4608 is not reviewed yet by the bot while all checks are passed.
> "Review required. At least 1 approving review is required by reviewers with write access."

I've manually requested the bot review your pull request.
