### ISSUE TITLE
Keep failing checks. All requested items are present

### ISSUE THREAD

**Issue by kotacode** [education/GitHubGraduation-2021#5882]
--- 
name: Dakota Craig                                                                                
institution: University of Georgia                                                                
quote: Programmer: A machine that turns coffee into code 
github_user: kotacode 
---

This is the content of my kotacode.md file in my _data/kotacode directory

The review says I need to include my github username, a name attribute, an institution attribute, and a quote attribute.

**Comment by drikdrick** [comment]
Well, I think you shouldn't use ':' to prevent failing. Hope it helps.

**Comment by Devansh2005** [comment]
@kotacode ,do check if the markdown is Invalid.

**Comment by kotacode** [comment]
> Well, I think you shouldn't use ':' to prevent failing. Hope it helps.

Thanks, I just copied the skeleton code from the readme. I'll try this.
