### ISSUE TITLE
#115 Completed everything

### ISSUE THREAD

**Issue by Chodylin** [education/GitHubGraduation-2021#5930]
I completed the Shipping form multiple times and correctly and have still not gotten any update or new checks. I should have passed as it says I have been able to merge.

**Comment by Luximo** [comment]
Yea same problem too but if all checked out then there probably isn't problem, should be good maybe?

**Comment by ManasUniyal** [comment]
The pull request is finally merged by a human. It will take time. The last PR merged successfully was made 12 hrs ago.
You need to be patient.
Cheers!!

**Comment by elisemoe** [comment]
There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
