### ISSUE TITLE
Here's How to successfully complete this 

### ISSUE THREAD

**Issue by HipsterSantos** [education/GitHubGraduation-2021#5959]
- [x] fork the repo
- [x] clone the repo
- [x] open the folder _data 
- [x] add your folder inside _data folder just like this _data/MyUser/MyUser.md(remember inside the folder _data add your own folder
- [x] after this done, commit all changes and give a push
- [x] push by type git push 
- [x] after that ,got to github refresh the page (option) click on contribute and then click on open pull request
- [x] open that request , check all checkbox  and the automatically this will close

**Comment by Luximo** [comment]
Come on, just follow the instructions exactly like you listed...

**Comment by Devansh2005** [comment]
put "x" between []---> like [x]

**Comment by Devansh2005** [comment]
@Luximo ! I just thought if he's asking about the ticks😁😁

**Comment by Luximo** [comment]
no way😅, just clearing doubts before the user get any more nervous completing this challenge... you know...

**Comment by imsamimalik** [comment]
My request has been marked as "Ready to merge". Will it be merged by them or we have to do somethin?

**Comment by Sgt-Miller** [comment]
one more thing, the bot that checks your profile name is case sensitive! So make sure folder name, file name and username in the file all have the proper case

**Comment by ManasUniyal** [comment]
Any ideas about the review criteria? 
>Is it 
- random or 
- `first come first serve` based

**Comment by Devansh2005** [comment]
@ManasUniyal , First come first serve basis according to the Instructions

**Comment by Akankshabhatt** [comment]
My pull request is approve but my data is not showing in the folder.

**Comment by Devansh2005** [comment]
👋 @Akankshabhatt , The PR #7167 got the label and the files is in correct folder. 👌

**Comment by Akankshabhatt** [comment]
Thanks!!

**Comment by HipsterSantos** [comment]
I thinks this should be greater than 5k  we still having pull request event today

**Comment by Devansh2005** [comment]
@HipsterSantos , the counts is for "first 5k Merged PR. "

**Comment by shaikhAbuzar** [comment]
Whenever I try to push it gives me the following error:

```bash
C:\Users\Shaikh Abuzar\Desktop\Projects\GitGrad\GitHubGraduation-2021>git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 595 bytes | 119.00 KiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: fatal error in commit_refs
To https://github.com/shaikhAbuzar/GitHubGraduation-2021.git
 ! [remote rejected] shaikhAbuzar -> shaikhAbuzar (failure)
error: failed to push some refs to 'https://github.com/shaikhAbuzar/GitHubGraduation-2021.git'
```

**Comment by adityanz** [comment]
the github * *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/adityanz/adityanz.md` exists*

**Comment by ahmad-khaqan** [comment]
Any idea how to do this from a Windows 10 device?

**Comment by muneersyed156** [comment]
Guys, my PR is showing as 'Ready to merge', but not yet merged, do we have to do that or the reviewers will do that?

**Comment by Devansh2005** [comment]
> the github * _Uh Oh! I've found some issues with where you have created your files!_
> _The required markdown file does not exist, please ensure the file `_data/adityanz/adityanz.md` exists_

@adityanz , "you got the label ready to merge" ✌😎.

**Comment by Devansh2005** [comment]
@muneersyed156 , we cannot merge it and have to wait for the owners of the repo to merge the PR.

**Comment by roshniverma21** [comment]
Can some one please tell me what i am doing wrong in PR #6694.

**Comment by Santhoshkumard11** [comment]
The first 5k PRs are merged!!!

**Comment by HipsterSantos** [comment]
Mine was merged how about yours?

**Comment by Santhoshkumard11** [comment]
yup done!!

**Comment by ayushjha952** [comment]
Is 5k PR's merged?

**Comment by ayushjha952** [comment]
I Created a pull request 2 days ago it has not been merged till now?

**Comment by adityaj48** [comment]
@ayushjha

> I Created a pull request 2 days ago it has not been merged till now?

Mine was merged this morning only so wait

**Comment by Aman22sharma** [comment]
> Guys, my PR is showing as 'Ready to merge', but not yet merged, do we have to do that or the reviewers will do that?

@muneersyed156 that will be done by reviewers
