### ISSUE TITLE
Uh Oh! I've found some issues with where you have created your files!

### ISSUE THREAD

**Issue by Mumtazbadar** [education/GitHubGraduation-2021#6097]
Getting above error while the file is there

Uh Oh! I've found some issues with where you have created your files!
The required markdown file does not exist, please ensure the file _data/Mumtazbadar/Mumtazbadar.md exists
Please ensure all changes are contained within the _data/Mumtazbadar/ directory. Invalid file paths:

_data/MumtazBadar/MumtazBadar.md
Feel free to re-request a review from me and I'll come back and take a look!

**Comment by benza613** [comment]
Your github username (not github display name) is Mumtazbadar (lowercase B) but are you trying to create MumtazBadar w/ uppercase B? 
Please be careful with the spelling and capitalization
