### ISSUE TITLE
Ready to merge

### ISSUE THREAD

**Issue by m-mahesh1812** [education/GitHubGraduation-2021#6454]
How to merge, it's only showing ready to merge not merged

**Comment by luizfelipers19** [comment]
I'm also waiting for my request to be merged. I THINK that only the owner of the repo can merge the request, so I THINK we have to wait by now.
Please, someone correct me if I'm wrong!

**Comment by luizfelipers19** [comment]
Well, I've just read the checklist we had to fill, and there's an item that says that a reviewer will merge our branches

**Comment by elisemoe** [comment]
> How to merge, it's only showing ready to merge not merged

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
