### ISSUE TITLE
Can any person who is graduating in 2022 -JUNE fill it?

### ISSUE THREAD

**Issue by Amrita0054** [education/GitHubGraduation-2021#6609]
* Please correct me if I am wrong!

**Comment by ManasUniyal** [comment]
No it is only for the students graduating in 2021.

**Comment by Amrita0054** [comment]
Ok, thankyou @ManasUniyal.

**Comment by Kritika-2000** [comment]
@ManasUniyal Hey one of my junior created a pull request which is ready to get merge but she is graduating in year 2022 , so if she delete her pull request now before it is merged will she still be eligible to fill this form for next year ?

**Comment by 99bcsagar** [comment]
no

**Comment by elisemoe** [comment]
The event is to celebrate the Class of 2021. The only requirements from us are -

1. You are a verified student with the GitHub Student Developer Pack
2. You have not participated in a previous GitHub Graduation event

If you would like to participate this year are are not a part of the Class of 2021, that is ok but please understand you will not be able to join in with your class in the future.

**Comment by Harindulk** [comment]
@elisemoe Will it be held in 2022? 🥲🥲
