### ISSUE TITLE
PR review criteria 

### ISSUE THREAD

**Issue by ManasUniyal** [education/GitHubGraduation-2021#6610]
Any ideas about the review criteria? 
>Is it 
- random or 
- `first come first serve` based

**Comment by harshita2216** [comment]
It is written first 5000 PRs. So I think it should be first come first serve. @ManasUniyal

**Comment by ME-ON1** [comment]
yes first 5000 with the required files.

**Comment by elisemoe** [comment]
Working hard to get through all of your pull requests! 💖

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. We are going through them in the order received and this will take us some time to get through everyone.
