### ISSUE TITLE
Feature Request: Open PRs to a "graduation" branch

### ISSUE THREAD

**Issue by TheBrenny** [education/GitHubGraduation-2021#6619]
I know 2MB isn't much, but on slow and/or unstable connections this can really disrupt some people from getting their contributions in on time.

```prompt
$ du -sh --apparent-size --exclude=./.git/* --exclude=./_data/* ./
178K    ./
$ du -sh --apparent-size --exclude=./.git/* ./
2.0M    ./
```

My idea to fix this (if you do see this as an issue) would be to have two branches: `main` and `graduation`.
- `main` would be responsible for holding the template file which graduates should modify.
- `graduation` would be the branch that PRs are published against.

This would also probably solve any merge conflicts, or any errors with cross-platform CR/LFs (if there are any). It would also save the environment from roughly 42g of pollution per 5000 downloads (inaccurate because of the linear growth of the repo as more merges get made). ([Source for data transmission per 140GB data](https://www.cmswire.com/digital-experience/calculating-the-pollution-effect-of-data/#:~:text=0.28*0.015%20=%200.0042%20kg%20of%20CO2%20for%20every%20GB%20streamed/transmitted))

I know 42 grams of pollution isn't much in the scheme of things (especially on GitHub 😅) but maybe it could be the beginning of some environmentally friendly workflows?

Definitely not possible this year, but something to think about for next year I guess... 🌳🌞🧊🌴

**Comment by elisemoe** [comment]
We'll look into ideas for next year 💖
