### ISSUE TITLE
Application GitHub Graduation 2021

### ISSUE THREAD

**Issue by nafiss-radzuan** [education/GitHubGraduation-2021#6679]
This pull request template will help you to complete an application to the Class of 2021. Use the checklist below to verify you have followed the instructions correctly.

Checklist

- [x] I have read the instructions on the README file before submitting my application.
- [x] I made my submission by creating a folder on the _data folder and followed the naming convention mentioned in the instructions () and markdown file.
- [x] I have submitted a swag shipping form.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I have added the event to my Calendar.

**Comment by nafiss-radzuan** [comment]
done. thank you.

**Comment by HariAcidReign** [comment]
This is incorrect. You should open a PR not an issue.
