### ISSUE TITLE
How will it be confirmed whether I graduated?

### ISSUE THREAD

**Issue by tralas** [education/GitHubGraduation-2021#6713]
How will it be confirmed whether I graduated? Because I haven't graduated yet.

**Comment by ME-ON1** [comment]
Student Developer pack.

**Comment by elisemoe** [comment]
There will be no confirmation of your graduation. 

The event is to celebrate the Class of 2021. The only requirements from us are -

1. You are a verified student with the GitHub Student Developer Pack
2. You have not participated in a previous GitHub Graduation event

If you would like to participate this year are are not a part of the Class of 2021, that is ok but please understand you will not be able to join in with your class in the future.
