### ISSUE TITLE
Pull Request Merge Sequence

### ISSUE THREAD

**Issue by ctanszeq** [education/GitHubGraduation-2021#6774]
Hi, I have a question regarding the Pull Request merge sequence. Shouldn’t it be a first come first serve basis where the first 5000 successful / correct pull request be merged? From the closed pull requests, it seems like some newer ones are being merged first instead of the earlier ones. Some pull requests from 8 hours ago are still open while some pull requests from a few minutes ago is already merged.

**Comment by adityaj48** [comment]
their pull request is Not merged yet because who are lacking something or doing it against the guidelines

**Comment by ctanszeq** [comment]
> their pull request is Not merged yet because who are lacking something or doing it against the guidelines

I understand, however there are some that passed the Check, and some are tagged “ready to merge” but have not been merged, which is why I’m confused. If it’s already tagged as “ready to merge”, why is it not merged? Also there are newer forks with “ready to merge” that are merged before the older “ready to merge” forks.

**Comment by ME-ON1** [comment]
Merge can only be done by the staff member and you will have to wait as there are more than  5K PR and its a FIFO

**Comment by adityaj48** [comment]
Have your folder successfully added I'm year book ? And can you see it ?

**Comment by ctanszeq** [comment]
> Have your folder successfully added I'm year book ? And can you see it ?
> […](#)

I posted my pull request 10 hours ago, and it had not been merged yet.

**Comment by adityaj48** [comment]
Mine get merged because I don't see any issue and I received a mail too for
successful pull request but I confused now did it added or not what I
should do now

**Comment by Gaojianli** [comment]
> Merge can only be done by the staff member and you will have to wait as there are more than 5K PR and its a FIFO

But my pr https://github.com/education/GitHubGraduation-2021/pull/1446 had not been merged yet, but this https://github.com/education/GitHubGraduation-2021/pull/5607 was merged

**Comment by tarunesh1234** [comment]
> > Merge can only be done by the staff member and you will have to wait as there are more than 5K PR and its a FIFO
> 
> But my pr #1446 had not been merged yet, but this #5607 was merged

pr #5607 has 0 checks and 0 file changes but still got merged.
waiting for mine #4566

**Comment by elisemoe** [comment]
Pull requests are being merged in the order they are received. I'll look into the cases you've linked above 💖
