### ISSUE TITLE
Not graduating, misunderstanding 

### ISSUE THREAD

**Issue by YashashwiniDixit** [education/GitHubGraduation-2021#7003]
By mistake I applied but not graduating this year, how can I revoke my application without losing the chance to apply some years later? (deleted the fork and closed the pull request already)

**Comment by Devansh2005** [comment]
If the PR is not merged you can apply for this again. No worries ✌✌

**Comment by YashashwiniDixit** [comment]
Okay thanks for the information, it was ready to merge but not merged and I closed it. So I guess won't be considered.
