### ISSUE TITLE
Few questions and Misunderstanding

### ISSUE THREAD

**Issue by janaSunrise** [education/GitHubGraduation-2021#7389]
I will be graduating in 2024, and I had misunderstood the concept. I thought it was for everyone who have the github graduation pack. I'm in 10th grade, and I'll be graduating in 2024 after 12th grade. My PR has bee closed by me, And apply when my chance comes.

And, My question is Will this be tracked every year who participates? If I'm in 10th grade, will I be still able to go? Asking since unsure, The PR changes added by me is removed, I'll be able to go for 2024 batch right?

Thanks a lot.

**Comment by Devansh2005** [comment]
Great going @janaSunrise. By 2024 you'll be deserving much more😎🎉🎉

**Comment by janaSunrise** [comment]
Thank you 😁 I just was a bit confused about this thing, Sorry for the nuisance and inconvenience!

**Comment by Devansh2005** [comment]
You are a great Champ to be welcomed by open source community 😎😎

**Comment by janaSunrise** [comment]
Thanks a lot! You too :D We all are here to grow and spread open source! Proprietary and such things would exist, but Open source is evergreen :)
