### ISSUE TITLE
I joined but I will graduate in 2022, can I still have a swag.

### ISSUE THREAD

**Issue by jacksssy** [education/GitHubGraduation-2021#7486]
I joined but I will graduate in 2022, can I still have a swag.

**Comment by Devansh2005** [comment]
#7486 , this PR might not come under 5000 merged PR. 😶😶

**Comment by jacksssy** [comment]
I did not join with this account and my main account is in the first 5000

**Comment by 99bcsagar** [comment]
NO

**Comment by elisemoe** [comment]
The event is to celebrate the Class of 2021. The only requirements from us are -

1. You are a verified student with the GitHub Student Developer Pack
2. You have not participated in a previous GitHub Graduation event

If you would like to participate this year are are not a part of the Class of 2021, that is ok but please understand you will not be able to join in with your class in the future.
