### ISSUE TITLE
Re-requesting a Review

### ISSUE THREAD

**Issue by GeraldKoYH** [education/GitHubGraduation-2021#7554]
Just completed the application. Would love a review again!

**Comment by elisemoe** [comment]
Looks like your PR is ready to merge ✨

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
