### ISSUE TITLE
pull request never reviewed

### ISSUE THREAD

**Issue by sandyskim** [education/GitHubGraduation-2021#7566]
hi! my pull request, #4817, has passed all the checks as of ~10 hours ago from opening this issue, but nobody/bot has reviewed it and it has been stuck at waiting for a reviewer since then. 😢 would i be able to get the @GitHub-Education-bot or someone manually assigned to my PR as a reviewer to approve it? thanks! 😀

**Comment by ME-ON1** [comment]
hi it looks like your checks have passed but bot hasn't added the label or comment. 

https://github.com/education/GitHubGraduation-2021/actions/runs/836730666

You might want to contact the main staff member for this. 

@ elisemoe  @ juanpflores

**Comment by Devansh2005** [comment]
@sanaro99 , Can you request the bot to review this again 🙄🙄.

**Comment by elisemoe** [comment]
I have manually requested a review on your pull request 👍
