### ISSUE TITLE
Pull request never reviewed #3251

### ISSUE THREAD

**Issue by nehamehta2110** [education/GitHubGraduation-2021#7590]
Hi, my PR #3251 passed all the checks but it is stuck as no reviewer has been assigned since 11 hours. Can someone manually assign a bot?

**Comment by Devansh2005** [comment]
@nehamehta2110 , try to comment on that PR mentioning the member @ juanpflores.

**Comment by ME-ON1** [comment]
your PR action error message was this. You were just unlucky this happened with you ! 
`Request quota exhausted for request GET /repos/{owner}/{repo}/contents/{path}`

Try contacting the staff owner as @Devansh2005  said

**Comment by elisemoe** [comment]
I have manually requested the bot review your pull request.

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. We are going through them in the order received and this will take us some time to get through everyone.
