### ISSUE TITLE
Submit error

### ISSUE THREAD

**Issue by AndreasFxPro** [education/GitHubGraduation-2021#7778]
Why bot says It looks like you still need to fill out the shipping form to continue?
I filled it out, but it says same error.

**Comment by ME-ON1** [comment]
double check if you have accpeted COC in shipping form with same username(name etc ) as written in your github username

**Comment by elisemoe** [comment]
Working hard to get through all of your pull requests! 💖

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. We are going through them in the order received and this will take us some time to get through everyone.
