### ISSUE TITLE
Will New PR be accepted if the bot wasn't working well for the previous PR

### ISSUE THREAD

**Issue by VedantKhairnar** [education/GitHubGraduation-2021#7828]
Old PR: #3858
New PR: #7805 

In old PR, bot said its ready to merge but never merged it.
- Was it some issue regarding the bot and the new PR with same contents was reviewed properly?
- Was I to create a new PR?
- Will I be considered into the first 5k?

**Comment by ME-ON1** [comment]
bot does not merge the changes
. It will be merge by the staff member. Wait and your first PR has a chance to get merge.

**Comment by VedantKhairnar** [comment]
In the old PR: 
  Bot added the label 'Ready for Merge' but no comment was made.

In the new PR, I got the label as well as the comment
```
Hi VedantKhairnar,
Welcome to graduation!

It looks like you're all set! Thanks for the graduation submission.
```

So should I proceed with the old PR or the new one?

**Comment by aleexnl** [comment]
you already closed Old PR, so just wait until the new one gets merged.

**Comment by VedantKhairnar** [comment]
It can be opened, right.

**Comment by elisemoe** [comment]
I've re-requested the bot to run on your first PR. Please close the second once you've confirmed it has run.

**Comment by VedantKhairnar** [comment]
Thanks Elise!! It worked! 
Just waiting for it to get merged.
