### ISSUE TITLE
File Could not be created!

### ISSUE THREAD

**Issue by Abhi-Dey** [education/GitHubGraduation-2021#7837]
unable to add file to the _data file.

**Comment by DesignrKnight** [comment]
Hey @Abhi-Dey even I had faced that issue. It seems that it is happening due to the large volume of traffic within a limited time. I would suggest trying again after some time as I was able to get mine merged yesterday

**Comment by Mr-codehunter** [comment]
i am also getting the same error.

**Comment by Dhruvacube** [comment]
me also
let us try after some time

**Comment by Mr-codehunter** [comment]
Yes

**Comment by arnav-deep** [comment]
Same Issue. Did anyone find any solution?

**Comment by ME-ON1** [comment]
what are you getting ??!

**Comment by Abhi-Dey** [comment]
hey guys! so about the issue i was facing( i.e., I was unable to add my file to _data0).....it got resolved on it’s own. @DesignrKnight you wre right, I just had to wait for sometime and then reapply. 
thank you all!
