### ISSUE TITLE
Can't push my changes to forked repo GitHubGraduation-2021

### ISSUE THREAD

**Issue by Dhruvacube** [education/GitHubGraduation-2021#7838]
# Can't push my changes to forked repo GitHubGraduation-2021
Whenever I try to push the changes it shows a 500 Error.
**Repo Link** : [Click Here](https://github.com/Dhruvacube/GitHubGraduation-2021)

## The Error:
`
remote: Internal Server Error. remote: fatal: unable to access 'https://github.com/Dhruvacube/GitHubGraduation-2021.git /': The requested URL returned error: 500
1
![2021-05-13 (1)](https://user-images.githubusercontent.com/34207400/118096665-491b1780-b3ef-11eb-96eb-3312ff14f1e4.png)

**Comment by KaustubhDamania** [comment]
Yes, even I'm getting the same error

**Comment by Devansh2005** [comment]
Try putting "-f" instead of "-u" @Dhruvacube , @KaustubhDamania .

**Comment by Dhruvacube** [comment]
> Try putting "-f" instead of "-u" @Dhruvacube , @KaustubhDamania .

tried but its not working
its giving the same error

**Comment by Komal7209** [comment]
@Dhruvacube  delete the repo from your local, try again cloning it and start over again... yesterday it was the same issue I was facing.... But it workedd for me like this without any command change

**Comment by Devansh2005** [comment]
Try checking your name & username using----> git config user.name & git config user.email to ensure you are doing the stuff with same credentials.

**Comment by Devansh2005** [comment]
@Komal7209 , why is this error popping up. Have you figured it out ?

**Comment by Komal7209** [comment]
@Devansh2005  how are you pushing changes to main repo, are u using any tool or through git bash only?

**Comment by Dhruvacube** [comment]
> @Dhruvacube delete the repo from your local, try again cloning it and start over again... yesterday it was the same issue I was facing.... But it workedd for me like this without any command change

okay lemme try

**Comment by Lamiv** [comment]
After about 100 tries, I was successful only for the bot to ask me to review again!

**Comment by Devansh2005** [comment]
@Komal7209 , I did it the same way using git bash yesterday. It worked perfectly fine for me.

**Comment by KaustubhDamania** [comment]
![image](https://user-images.githubusercontent.com/33577657/118102173-1294cb00-b3f6-11eb-805c-4658beb83694.png)
I'm getting this error too sometimes

**Comment by Dhruvacube** [comment]
Finally after sometime now the pull request is done! Thanky ou all !

**Comment by KaustubhDamania** [comment]
@Dhruvacube same here! thank you everyone for your help :smile:
