### ISSUE TITLE
Remote  Rejected whenever I try to push

### ISSUE THREAD

**Issue by shaikhAbuzar** [education/GitHubGraduation-2021#7881]
I am getting the following error while trying to push

```bash
C:\Users\Shaikh Abuzar\Desktop\Projects\GitGrad\GitHubGraduation-2021>git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 595 bytes | 119.00 KiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: fatal error in commit_refs
To https://github.com/shaikhAbuzar/GitHubGraduation-2021.git
 ! [remote rejected] shaikhAbuzar -> shaikhAbuzar (failure)
error: failed to push some refs to 'https://github.com/shaikhAbuzar/GitHubGraduation-2021.git'
```

**Comment by Dhruvacube** [comment]
man even with me also same case

**Comment by Skyquek** [comment]
I was facing the same problem. Solved it by upload my file through GitHub site.

**Comment by Dhruvacube** [comment]
I am unable to do it from direct upload also

**Comment by Devansh2005** [comment]
How can this error come up pushing to the cloned repo. Traffic is surely not the case. I'm confused 🙄🙄🙄🙄

**Comment by arnav-deep** [comment]
Same Issue. Did anyone find any solution?

**Comment by Komal7209** [comment]
@shaikhAbuzar delete the repo from your local, try again cloning it and start over again... yesterday it was the same issue I was facing.... But it workedd for me like this without any command change

**Comment by henryStelle** [comment]
I ran into this issue too and just used the web client to make the file and open the PR - which was annoying, but worked.

**Comment by ShubhayanS** [comment]
I guess github has an issue when 100+ PR are there while pushing locally

**Comment by Rajpra786** [comment]
1. First you should fork the repo
2. Clone the forked repo
3. update and push there
4. In the web client, after push, you will see a button for contribution in forked repo, when you click on it, you will have an option to make pull request. 




I hope it helps :)
