### ISSUE TITLE
Re-requesting for a review

### ISSUE THREAD

**Issue by Komal7209** [education/GitHubGraduation-2021#7888]
Hi, github reviewers, I had corrected my pr as per instructed to make changes, please do review once again :)

**Comment by Devansh2005** [comment]
#4398 , #2351 - In these PR's Checks were failed and incomplete.

**Comment by Komal7209** [comment]
@Devansh2005 Yes they were, yesterday I was trying to resolve all that but then I was able to fix that latest one #4398

**Comment by Devansh2005** [comment]
@Komal7209 , do check this PR-- #7954 . Tag them 😏😏

**Comment by elisemoe** [comment]
I've re-requested the bot to run on your pull request.
