### ISSUE TITLE
@GitHub-Education-bot test and approve this pls, it's been 2 hrs.

### ISSUE THREAD

**Issue by navinbarnwal** [education/GitHubGraduation-2021#7963]
@GitHub-Education-bot test and approve this pls, it's been 14 hrs.

_Originally posted by @navinbarnwal in https://github.com/education/GitHubGraduation-2021/issues/4204#issuecomment-840097771_

**Comment by ArpitArunKumaar** [comment]
![Screen Shot 2021-05-13 at 3 06 52 PM](https://user-images.githubusercontent.com/54761690/118117592-df096f00-b3fc-11eb-83b0-1d206a88a8de.png)
get it fixed first..

**Comment by navinbarnwal** [comment]
> ![Screen Shot 2021-05-13 at 3 06 52 PM](https://user-images.githubusercontent.com/54761690/118117592-df096f00-b3fc-11eb-83b0-1d206a88a8de.png)
> get it fixed first..

@ArpitArunKumaar If you don't mind would you pls help me with the issue here?

**Comment by elisemoe** [comment]
I've re-requested the bot to run on your pull request.

**Comment by navinbarnwal** [comment]
> I've re-requested the bot to run on your pull request.

Thankx @elisemoe , I don't know what these kids feel commenting about issues with inefficient knowledges..

**Comment by ArpitArunKumaar** [comment]
> > I've re-requested the bot to run on your pull request.
> 
> Thankx @elisemoe , I don't know what these kids feel commenting about issues with inefficient knowledges..

you're the one who can't figure your own shit and call us kids lmao

**Comment by navinbarnwal** [comment]
> > > I've re-requested the bot to run on your pull request.
> > 
> > 
> > Thankx @elisemoe , I don't know what these kids feel commenting about issues with inefficient knowledges..
> 
> you're the one who can't figure your own shit and call us kids lol

@ArpitArunKumaar  The issue was with the bot as the Title says `test and approve this pls, it's been 2 hrs` and as she mentioned, the solution was to re-run the bot on this PR. There wasn't any issue from my side. You being on the other side had the authority to review or re-run the test, but you instead couldn't resist yourself from your stupid mocking behaviour right?

**Comment by ArpitArunKumaar** [comment]
> > > > I've re-requested the bot to run on your pull request.
> > > 
> > > 
> > > Thankx @elisemoe , I don't know what these kids feel commenting about issues with inefficient knowledges..
> > 
> > 
> > you're the one who can't figure your own shit and call us kids lol
> 
> @ArpitArunKumaar The issue was with the bot as the Title says `test and approve this pls, it's been 2 hrs` and as she mentioned, the solution was to re-run the bot on this PR. There wasn't any issue from my side. You being on the other side had the authority to review or re-run the test, but you instead couldn't resist yourself from your stupid mocking behaviour right?

i got the error and fixed it on my own bruh

**Comment by ArpitArunKumaar** [comment]
> > > > > I've re-requested the bot to run on your pull request.
> > > > 
> > > > 
> > > > Thankx @elisemoe , I don't know what these kids feel commenting about issues with inefficient knowledges..
> > > 
> > > 
> > > you're the one who can't figure your own shit and call us kids lol
> > 
> > 
> > @ArpitArunKumaar The issue was with the bot as the Title says `test and approve this pls, it's been 2 hrs` and as she mentioned, the solution was to re-run the bot on this PR. There wasn't any issue from my side. You being on the other side had the authority to review or re-run the test, but you instead couldn't resist yourself from your stupid mocking behaviour right?
> 
> i got the same error and fixed it on my own bruh

**Comment by navinbarnwal** [comment]
> > > > > > I've re-requested the bot to run on your pull request.
> > > > > 
> > > > > 
> > > > > Thankx @elisemoe , I don't know what these kids feel commenting about issues with inefficient knowledges..
> > > > 
> > > > 
> > > > you're the one who can't figure your own shit and call us kids lol
> > > 
> > > 
> > > @ArpitArunKumaar The issue was with the bot as the Title says `test and approve this pls, it's been 2 hrs` and as she mentioned, the solution was to re-run the bot on this PR. There wasn't any issue from my side. You being on the other side had the authority to review or re-run the test, but you instead couldn't resist yourself from your stupid mocking behaviour right?
> > 
> > 
> > i got the same error and fixed it on my own bruh

I can very well see your 5 PR's. Good you did it... Nice talking to you.

**Comment by ArpitArunKumaar** [comment]
> > > > > > > I've re-requested the bot to run on your pull request.
> > > > > > 
> > > > > > 
> > > > > > Thankx @elisemoe , I don't know what these kids feel commenting about issues with inefficient knowledges..
> > > > > 
> > > > > 
> > > > > you're the one who can't figure your own shit and call us kids lol
> > > > 
> > > > 
> > > > @ArpitArunKumaar The issue was with the bot as the Title says `test and approve this pls, it's been 2 hrs` and as she mentioned, the solution was to re-run the bot on this PR. There wasn't any issue from my side. You being on the other side had the authority to review or re-run the test, but you instead couldn't resist yourself from your stupid mocking behaviour right?
> > > 
> > > 
> > > i got the same error and fixed it on my own bruh
> 
> I can very well see your 5 PR's. Good you did it... Nice talking to you.

bye good luck wid ur submission

**Comment by elisemoe** [comment]
I've deleted this conversation as it's not relevant to the Issue or helpful.
