### ISSUE TITLE
Request For merge as all checks passed

### ISSUE THREAD

**Issue by prakhargupt00** [education/GitHubGraduation-2021#7969]
Hi, 
My PR "Add entry to yearbook 2021" has passed all checks and there are no conflicts and is ready for merge.

**Comment by Devansh2005** [comment]
Yes , it will be merged by the community members. Bot can give the labels only.

**Comment by Suman-programmer** [comment]
Is it first come first serve basis or randomly?

**Comment by Devansh2005** [comment]
@Suman-programmer, according to the documentation, First come first serve.

**Comment by elisemoe** [comment]
Working hard to get through all of your pull requests! 💖

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
