### ISSUE TITLE
Re-Review My Application

### ISSUE THREAD

**Issue by AnandD007** [education/GitHubGraduation-2021#8017]
I have filled my swag form before raising my Pull Request but I've got an issue and my PR is non-editable to make changes. So please review my application as soon as possible.

My PR - #7735

**Comment by Devansh2005** [comment]
@AnandD007, make sure that you have entered the correct username in that form(Case sensitive).

**Comment by sushrut111** [comment]
@AnandD007 You can edit files in your PR like this:
- Go to files changed: https://github.com/education/GitHubGraduation-2021/pull/7735/files
- Click on 3 vertical dots below "Review changes" button on that page
- Click on edit

Why do you need to edit the file? You may have filled the goodies form but there must be some typo in what you filled in.

**Comment by AnandD007** [comment]
Yes Sir. I need to solve the typo on the third line - **Live, Work, Create** quote change to **Live Work Create**. But it is showing that the file is non-editable when I'm committing the edited file.

**Comment by sushrut111** [comment]
You could either follow what I said to edit it or edit it in your own fork, The pull request will be updated automatically.

**Comment by AnandD007** [comment]
I have made correct changes in my Application Sir. So Please Kindly merge PR to Main repo

**Comment by sushrut111** [comment]
@AnandD007 I am not a repository owner. The automation and the owners will take care of that.

**Comment by AnandD007** [comment]
Ok, Thank You Sir for guiding me.

**Comment by elisemoe** [comment]
> I have filled my swag form before raising my Pull Request but I've got an issue and my PR is non-editable to make changes. So please review my application as soon as possible.
> 
> My PR - #7735

I've re-requested the bot to run on your pull request.
