### ISSUE TITLE
Request for review my PR Username: SamyakGangwal PR: #821

### ISSUE THREAD

**Issue by SamyakGangwal** [education/GitHubGraduation-2021#8194]
I had opened a PR before 1,000 PR's were made, but my PR is not reviewed yet, it has passed all checks

**Comment by elisemoe** [comment]
Working hard to get through all of your pull requests! 💖

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
