### ISSUE TITLE
Bot skipped over #4227, all checks passed

### ISSUE THREAD

**Issue by b-coimbra** [education/GitHubGraduation-2021#8252]
It seems my PR  (#4227) has been skipped by the bot since yesterday (over 16 hours ago), even though all the checks have passed.

Is there something I can do to fix this? I don't want to create another PR and lose the merge queue.

Thanks.

**Comment by ME-ON1** [comment]
Hi your PR action has this error 
`Error: Request failed with status code 404` 
it happened with other people also. I think you can tag the main staff or `amend` your commit to trigger a new action on your PR.

**Comment by b-coimbra** [comment]
I pushed a new commit, now it's stuck on "Getting grades", not sure why...

**Comment by brneor** [comment]
Try re-requesting a review.

**Comment by b-coimbra** [comment]
@brneor The bot wasn't added as a reviewer, so I can't do that:
![image](https://user-images.githubusercontent.com/17071218/118128623-87a1d980-b3d1-11eb-8226-33f7686f983c.png)

**Comment by Variiuz** [comment]
You can convert to draft and revert that, that also starts a new action.

**Comment by b-coimbra** [comment]
@Variiuz That did the trick, the bot immediately started to check my PR.

Thank you everyone, closing the issue now.
