### ISSUE TITLE
SJ029626 Graduation Merge

### ISSUE THREAD

**Issue by SJ029626** [education/GitHubGraduation-2021#8262]
Please look at my merge request: https://github.com/education/GitHubGraduation-2021/pull/8230

**Comment by krishnadevz** [comment]
hey they said don't tag and please don't misbehave like opening spam issues and also that is for the first 5000 pull requests take care :)

**Comment by SJ029626** [comment]
Oh I wasn't trying to do that but I saw some issues open so I also thought of opening one and tagging mine. @krishnadevz

**Comment by krishnadevz** [comment]
ok bro
