### ISSUE TITLE
ptech12 still not merged, PR #4407

### ISSUE THREAD

**Issue by ptech12** [education/GitHubGraduation-2021#8311]
## Bot accepted the request, but still my folder was not merged
[https://github.com/education/GitHubGraduation-2021/pull/4407](url)

**Comment by vp1099** [comment]
it will take time , till now only 650-660 pull requests have been merged .
 
so going by this rate it can take 2-4 days

keep calm and since your pull request is 4407 , i am very sure it will be merged

**Comment by hitiksaini** [comment]
> it will take time , till now only 650-660 pull requests have been merged .
> 
> so going by this rate it can take 2-4 days
> 
> keep calm and since your pull request is 4407 , i am very sure it will be merged

Same for me, I did it around 2AM today and the PR IS still not merged. 

https://github.com/education/GitHubGraduation-2021/pull/4968 

I hope this comes under 5k, What you say?

**Comment by vp1099** [comment]
Be hopeful that's all I can say ! Any PR under 5000 has a very strong chance of being merged because it is on a first come first serve basis

**Comment by MainakRepositor** [comment]
I have my PR #4282 in the merge queue, approved by the bot. I actually had made 2 merges by mistake and so I deleted one and with it, the forked repo too got deleted. But in the merge queue my PR#4828 is still being displayed. Will that cause any issue? Please tell anyone!

**Comment by vp1099** [comment]
As long as Any One of your PR is labelled as 'Ready to be Merged' . there's no reason to worry .

**Comment by MainakRepositor** [comment]
Thank you so much brother 😊@vp1099

**Comment by elisemoe** [comment]
Working hard to get through all of your pull requests! 💖

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
