### ISSUE TITLE
How much time it takes to merge the pull request

### ISSUE THREAD

**Issue by Spandan09** [education/GitHubGraduation-2021#8344]
The GitHub bot has reviewed my pull request and it has been labeled as ready to merge. 
So how much time after that is needed to merge my pull request into the main repo?

**Comment by vp1099** [comment]
it is done  serially ,  my pull  request is 2127 still did not get merged , so it can take  upto 2-3 days

**Comment by Spandan09** [comment]
So is it.
Mine is 4255 so it will take a lot of time I guess. But I am seeing random numbers being merged in the repo. How is that?

**Comment by vp1099** [comment]
its not random ,  it is done serially only , but the thing is many pull requests are not valid , so those are skipped and the next valid pull request is merged

**Comment by Spandan09** [comment]
Yeah, you got a point. 
Ughh this lockdown has taken a toll on my basic reasoning 😂

**Comment by faizalanwar** [comment]
maybe we need to be patient in a moment

**Comment by vp1099** [comment]
@Spandan09 i feel you 

anyway  cheers!!

**Comment by Spandan09** [comment]
Cheers mate and thank you!
