### ISSUE TITLE
#3163 Passed Check 18 Hours Ago; Still Not Approved for Merge

### ISSUE THREAD

**Issue by huesca12** [education/GitHubGraduation-2021#8408]
#3163 needs to be reviewed

**Comment by daniil-lebedev** [comment]
I think they are having technical problems. Mine was approved and has a ready to merge sticker but still haven't merge. Only 2 people are merging the requests. You will have to wait for a few days I think. They barely got to 1000th request.

**Comment by ME-ON1** [comment]
You haven't got the label yet of Ready to merge . There is an error in your Action.  
You can convert to draft and revert that, that also starts a new action or call and make a label for your PR.

**Comment by huesca12** [comment]
@ME-ON1 

I thought I passed the check correctly. Do I need to pass it again or something?

**Comment by elisemoe** [comment]
Working hard to get through all of your pull requests! 💖

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. This will take us some time to get through everyone but we're working hard to get there! 😁
