### ISSUE TITLE
I registered with my brother's student email, can I join?

### ISSUE THREAD

**Issue by wondeq** [education/GitHubGraduation-2021#8411]
Hi. I registered with my brother's student email, can I join?

**Comment by ME-ON1** [comment]
Register with your email , its for your graduation not anyone else.

P.S. Identity theft is not a joke.

**Comment by DevPranavSharma** [comment]
> Register with your email , its for your graduation not anyone else.
> 
> P.S. Identity theft is not a joke.

Millions of families suffer every year

**Comment by tunaysalar** [comment]
No I didn't steal, I got permission from my brother

**Comment by wondeq** [comment]
No I didn't steal, I got permission from my brother

**Comment by vp1099** [comment]
Please Avoid Using Credentials that are Not your Own. 
PR'S FOUND WITH MALPRACTICES WILL BE SCRAPPED AND NOT BE MERGED 

Thank You 
GitHub Team
vp1099

**Comment by elisemoe** [comment]
> Hi. I registered with my brother's student email, can I join?

No. This is against GitHub's terms of service. You may only register with your own personal email and GitHub account. Doing otherwise could result in accounts being banned or removed from the platform.
