### ISSUE TITLE
Getting grades error at entry run point

### ISSUE THREAD

**Issue by dipuchaudhary** [education/GitHubGraduation-2021#8498]
when I tried to run my code in Actions with Graduation helper workflow it is giving getting grades error at the entry run point. Here's the log screenshot which I'm getting while  running in workflows
[
![image](https://user-images.githubusercontent.com/34309829/118137825-5bb04380-b425-11eb-90f3-de8a002d62d4.png)

](url)
Please help me out to resolve this issues

**Comment by bhawesh2002** [comment]
Fill the swag form.Then create/modify/edit your commit to github graduation as _data/your_username/your_username.md.
Add the following to your_username.md
---
name: FULLNAME-OR-NICKNAME # No longer than 28 characters
institution: INSTITUTION-NAME 🚩 # no longer than 58 characters
quote: YOUR-SENIOR-QUOTE # no longer than 100 characters, avoid using quotes(") to guarantee the format remains the same.
github_user: YOUR-GITHUB-USERNAME
---

**Comment by dipuchaudhary** [comment]
> ## Fill the swag form :- https://airtable.com/shrM5IigBuRFaj33H
> Then create/modify/edit your commit to github graduation as _data/your_username/your_username.md.
> Add the following to your_username.md
> ## name: FULLNAME-OR-NICKNAME # No longer than 28 characters
> institution: INSTITUTION-NAME 🚩 # no longer than 58 characters
> quote: YOUR-SENIOR-QUOTE # no longer than 100 characters, avoid using quotes(") to guarantee the format remains the same.
> github_user: YOUR-GITHUB-USERNAME

I have already filled the swag form though I'm getting the error.

**Comment by elisemoe** [comment]
It looks like your PR is ready to merge and will be manually reviewed in the order received! 💖

**Comment by dipuchaudhary** [comment]
LGTM! thanks
