### ISSUE TITLE
pull request #2384- Was approved yesterday but not merged yet!

### ISSUE THREAD

**Issue by jasleen101010** [education/GitHubGraduation-2021#8710]
Hi there!

Creating this issue in case my pull request was missed!
It got approved yesterday and got the "Ready to Merge" label but has not been merged yet!

**Comment by AndreasFxPro** [comment]
How did you fix it?

**Comment by jasleen101010** [comment]
hi there! so i saw this issue thread about how the merging is a manual process and is being done serially! so we gotta wait :D that is why is closed my issue for now!

**Comment by jasleen101010** [comment]
here's the link to the issue i mentioned https://github.com/education/GitHubGraduation-2021/issues/8599
