### ISSUE TITLE
Can't merge :(

### ISSUE THREAD

**Issue by AndreasFxPro** [education/GitHubGraduation-2021#8784]
I have label ready to merge, but i don't see button named merge
What i need to do?

**Comment by ME-ON1** [comment]
You won't merge. Only staff members has the right to merge. 

Sit back and relax

**Comment by viditvarshney** [comment]
@AndreasFxPro You don't have to worry about it. Only the members has the access to merge with the main.

**Comment by elisemoe** [comment]
Only to wait :) 

There's both an automated and manual review of each PR. The automated review will verify file paths, character counts, etc. of your pull request. Once this check is complete, a "ready to merge" label is applied to your PR. Once this label is present, our team does a manual check to verify that everything meets the event Code of Conduct. We are going through them in the order received and this will take us some time to get through everyone.
