### ISSUE TITLE
Cant' Merge

### ISSUE THREAD

**Issue by JarrelThomas** [education/GitHubGraduation-2021#8831]
All the file paths are correct but it won't let me merge

**Comment by viditvarshney** [comment]
Mention your PR here

**Comment by JarrelThomas** [comment]
#7506

**Comment by diksham1** [comment]
You can't change README.md file

**Comment by elisemoe** [comment]
As mentioned by @diksham1, please revert your changes to the readme file. Your pull request should show one file changed.

![Screen Shot 2021-05-13 at 1 42 52 PM](https://user-images.githubusercontent.com/6633808/118185283-36094700-b3f1-11eb-9c67-e22a1a024b2a.png)
