### ISSUE TITLE
getting grades waiting for status to be reported PR: #821

### ISSUE THREAD

**Issue by SamyakGangwal** [education/GitHubGraduation-2021#8875]
I have passed every check yet I am getting  this status. Can anyone please help me with this?
![image](https://user-images.githubusercontent.com/30174059/118182668-e8bfc080-b456-11eb-8761-914817a92fc6.png)

**Comment by elisemoe** [comment]
Hi @SamyakGangwal 👋 It looks like you'll need to [verify your student status here](https://education.github.com/discount_requests/student_application?utm_source=2021-06-05-GitHubGraduation) before requesting the bot to do another review.
