### ISSUE TITLE
Can't get past verification PR #2058

### ISSUE THREAD

**Issue by NicoAICP** [education/GitHubGraduation-2021#8890]
Hello, i have an issue that my pr is not accepted due to not having a student pack.

The issue is, i do have a student pass currently. Atleast i still have the perks from it and requested it back in October of last year
![image](https://user-images.githubusercontent.com/24915669/118184836-1fd4a880-b43c-11eb-9f16-4710f8da1afb.png)

THe pr in quesiton is #2058

**Comment by NicoAICP** [comment]
Seems to be an issue with a bot, after re reviewing it it passed

**Comment by elisemoe** [comment]
Looks like the bot has updated with your student status :) our team will be by shortly to merge!
