### ISSUE TITLE
Accidentally clicked on merge after verified commit

### ISSUE THREAD

**Issue by ctanszeq** [education/GitHubGraduation-2021#8978]
Hi, my pull request is #3260 
The first commit, I did everything correctly, and it passed the check.
However, after I created the pull request, I accidentally clicked on the merge, and then the check is not running anymore. After manually running the check, it is failing due to an entry point error.
To fix that, I tried adding a third commit to reverse the merge, but it seems like it did not work. Is there a way to remove the two latter commits and only leave the first verified commit in the pull request? 
Thanks in advance.

**Comment by vp1099** [comment]
Hi there ! I have looked at your PR and I am further tagging @elisemoe  to take a look at the problem . 
Hopefully this issue will be resolved soon ! 

Cheers !

**Comment by ctanszeq** [comment]
This issue is solved! Thank you @vp1099 and @elisemoe !
