### ISSUE TITLE
Pull request not showing in the folder

### ISSUE THREAD

**Issue by Luximo** [education/GitHubGraduation-2021#8990]
i cant't seem to find my name in it, what wrong?

_data/Luximo/Luximo.md

**Comment by vp1099** [comment]
Can you please Mention your PR Number So I can take a look ? 

Cheers !

**Comment by Luximo** [comment]
Where can i find such number please?

**Comment by Luximo** [comment]
This? ec42f1a?

**Comment by Luximo** [comment]
This? 41d3452?

**Comment by vp1099** [comment]
I guess what you have done is fork the repository and committed the files . 

I could no find your PR !

ARE YOU SURE YOU HAVE CREATED A PR ?

**Comment by Luximo** [comment]
Yes, i did...

![image](https://user-images.githubusercontent.com/56436632/118199732-b9db2780-b421-11eb-9c39-1e1138ba1c40.png)

**Comment by Luximo** [comment]
I have updated it, did you see it? #8996

**Comment by Luximo** [comment]
![image](https://user-images.githubusercontent.com/56436632/118200098-6ae1c200-b422-11eb-8e2d-1e36cf0b8a66.png)

**Comment by vp1099** [comment]
Yes I see it Now. !

Your PR #8996 is now all set to be Merged by the owners 

But since your PR is 8996 it might take some time  for the merge to happen depending upon the availability of slots , since it is limited only to the top 5000 PR's

Cheers !

**Comment by Luximo** [comment]
Oh my, what's the total number climbing so far?

**Comment by vp1099** [comment]
2,366 PR's have been Merged Up untill this moment ! 

That leaves us with 2,364 available slots! 

So we hope That your PR makes It to the cut !!

**Comment by vp1099** [comment]
Also I may request You to close this isse If all your queries were answered ! This will help use resolve other issues in a quick way 

Thanks !

**Comment by Luximo** [comment]
Sure, and thanks...

**Comment by Luximo** [comment]
To be sure, it is after my PR has been added then i'll see my name in the data github education main folder?

**Comment by vp1099** [comment]
Yes that is correct!

**Comment by Luximo** [comment]
Thanks...
