### ISSUE TITLE
New PR due to bot issues on the first one.

### ISSUE THREAD

**Issue by brneor** [education/GitHubGraduation-2021#9003]
My first pull request got messed up by our dear bot (#5311). I explained the details here: https://github.com/education/GitHubGraduation-2021/issues/8599#issuecomment-840868760

As suggested by @elisemoe in https://github.com/education/GitHubGraduation-2021/issues/8599#issuecomment-840865152 I created a new PR: #9000. Let's hope this beautiful round pr number brings me some luck this time! 😄

**Comment by praveenscience** [comment]
Damn, you're lucky man! #9000! 🔥

**Comment by Luximo** [comment]
Gosh, perfect thousand!😅💪

**Comment by elisemoe** [comment]
🎉
