### ISSUE TITLE
Machine Overriden and In a Private Workgroup Help

### ISSUE THREAD

**Issue by NetTunerFookHax** [education/GitHubGraduation-2021#9039]

**Comment by vp1099** [comment]
i didnt quite get what the issue is ? 
Could you share more details?

**Comment by elisemoe** [comment]
> i didnt quite get what the issue is ?
> Could you share more details?

Thanks for the follow up @vp1099 😁

**Comment by NetTunerFookHax** [comment]
Duplicate of #
