### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by harizz-s** [education/GitHubGraduation-2021#9078]
I have followed all procedures correctly , still i find the following errors in my PR. I don't know what i have done wrong here. Need help.
![image](https://user-images.githubusercontent.com/63995684/118213546-cc8a4680-b48b-11eb-9a5a-a4635c98ffa6.png)

PR -> #2944 .

Thanks :)

**Comment by adityanz** [comment]
You gotta wait if you just got the developer pack. Keep clicking the three dots on the bot and click re check

**Comment by harizz-s** [comment]
The bot solved the problem automatically.  Thanks for the reply @adityanz
