### ISSUE TITLE
PR merged but cant see my files and commit in main

### ISSUE THREAD

**Issue by alindk19** [education/GitHubGraduation-2021#9107]
I created this https://github.com/education/GitHubGraduation-2021/pull/4258 PR and it is merged now. But cannot see my files in _data folder.

In attached pic there is no folder named alindk19, and this is the latest pull
![Screenshot (131)](https://user-images.githubusercontent.com/37773803/118218704-9ea9ff80-b495-11eb-9640-74fdb5971c2c.png)

**Comment by vp1099** [comment]
I looked into your PR . There seems to be an issue with the merging process. 

I have further tagged @elisemoe to look into this issue and hopefully resolve this issue as quickly as possible.

Cheers !

**Comment by alindk19** [comment]
My first pull request(https://github.com/education/GitHubGraduation-2021/pull/4258) got messed up by bot during merge.
As suggested by @elisemoe in the comment ( https://github.com/education/GitHubGraduation-2021/pull/4258#issuecomment-840991438), created this new PR ( https://github.com/education/GitHubGraduation-2021/pull/9108 ).
@vp1099 please look into this.
