### ISSUE TITLE
Closed Pull Request by mistake

### ISSUE THREAD

**Issue by prasadnitesh202** [education/GitHubGraduation-2021#9253]
I had closed pull request by mistake
prasadnitesh202-commit #1256 
I just reopened it.Would my submissions be considered?

**Comment by Devansh2005** [comment]
@prasadnitesh202, The submission for the open PR will be considered. Make sure you get the label "ready to merge" for making a successful PR.

**Comment by prasadnitesh202** [comment]
I had received ready to merge tag. My PR number was #1256. But after that I had closed it by mistake. 
I reopened it today

**Comment by Devansh2005** [comment]
You had that label for this PR. It will be merged by the Repo Owners.🎉
