### ISSUE TITLE
Please do review my PR once again

### ISSUE THREAD

**Issue by Komal7209** [education/GitHubGraduation-2021#9295]
Hi , github reviewers , I have now finally changed the path, please do review , if there are any other minor things too left...

**Comment by Komal7209** [comment]
51f8dba5ae094d0f30c7b487ede8d78aa5a23051  Here's my commit number

**Comment by Komal7209** [comment]
@elisemoe Could you pls review my pr once again

**Comment by Luximo** [comment]
What's your PR number?

**Comment by Komal7209** [comment]
> What's your PR number?

#4398
