### ISSUE TITLE
please merge my request

### ISSUE THREAD

**Issue by sidag99** [education/GitHubGraduation-2021#9338]
please approve this

_Originally posted by @sidag99 in https://github.com/education/GitHubGraduation-2021/issues/4790#issuecomment-841138153_

**Comment by praveenscience** [comment]
Dude, it's been approved already. Would you like to close this issue? 🤔

**Comment by sidag99** [comment]
i meant merge this 😬. sorry

**Comment by praveenscience** [comment]
They're going in a queue, so please be patient... 🔥 Your turn will definitely come. No use in creating a new issue here. Think what happens if 9000 people create an issue to merge? 🤔 

Would you now like to close this? Just asking. 😅

**Comment by sidag99** [comment]
thanks for helping
