### ISSUE TITLE
Pull Request for GitHubGrad'21

### ISSUE THREAD

**Issue by zaibidev** [education/GitHubGraduation-2021#9372]
I have completed all these tasks given below just approve this:
Checklist ✅
 I have read the instructions on the README file before submitting my application.
 I made my submission by creating a folder on the _data folder and followed the naming convention mentioned in the instructions (<username>) and markdown file.
 I have submitted a swag shipping form.
 I have used the Markdown file template to add my information to the Year Book.
 I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
 I understand I should not tag or add a reviewer to this Pull Request.
 I have added the event to my Calendar.

**Comment by vp1099** [comment]
I request you to kindly close this issue .
Your PR is recorded and will be merged Serially

**Comment by elisemoe** [comment]
@zaibidev I do not see a pull request from your user name. Please comment a link to your pull request here if you believe there has been a mistake.

**Comment by zaibidev** [comment]
https://github.com/education/GitHubGraduation-2021/pull/9850

https://github.com/education/GitHubGraduation-2021/pull/9850/commits/0e98e18fd83410f813397f42584d3283045913d5
Check  above given links.
Thanks!

**Comment by elisemoe** [comment]
Thanks for the update @zaibidev! It looks like the bot has provided feedback. Please make the requested changes and we will be by to merge the pull request once ready ✨

**Comment by zaibidev** [comment]
no maam, its me zohaib follow the link to merge.
https://github.com/zaibidev/GitHubGraduation-2021/commit/4ab54aead5951d30ea655dbf74eecea0afc8f8d9
