### ISSUE TITLE
PR'S UNDER #3599 ,PAY ATTENTION , READ THIS THREAD CAREFULLY! [MERGE REQUESTS FOR PR BELOW #3599]

### ISSUE THREAD

**Issue by vp1099** [education/GitHubGraduation-2021#9450]
If your PR number is below #3599 and has passed all checks and has the label "Ready for Merge" and has not been merged Yet .
PLEASE LEAVE YOUR PR NUMBERS IN THE COMMENTS BELOW ,SO the Owners CAN LOOK INTO IT .

**Comment by chaitanyasjoshi** [comment]
#2700

**Comment by ctanszeq** [comment]
#3260

**Comment by TheUltimateAbsol** [comment]
What if it's passed all checks and doesn't have the label "Ready for Merge" [#3220](https://github.com/education/GitHubGraduation-2021/pull/3220)

**Comment by ctanszeq** [comment]
> #3260

This has already been merged!

**Comment by vp1099** [comment]
@ctanszeq Congratulations!! Your PR has been Merged 🎉🎉

**Comment by anshobrii** [comment]
# Hey, I see the last PR merged is #9000 and much higher PR merged but  My PR is #4522  and not yet merged since 2 days ago. Since it follows with first come first serve, is there any chance that my PR is skipped to be merged? Any reasons why?

**Comment by U-c0de** [comment]
@vp1099  How can #9000 PR can be merged

**Comment by vp1099** [comment]
@U-c0de @anshobrii The #9000 PR was merged because it is a PR which was created for a PR Against an earlier PR which had an error due to a bug in the BOT

**Comment by vs74** [comment]
My PR is #2054. Due to the weird behavior of the bot, I closed this PR and reopened another PR #8946. I kindly request you to look into it. I noticed the bot issue has been fixed but I'm unable to reopen my PR #2054 now.

Any leads on this will be highly appreciated.

**Comment by vs74** [comment]
@vp1099 can you reopen this issue as there are lot of folks whose PR under 3599 haven't been merged. 
Thanks!!
