### ISSUE TITLE
[Help]PR got closed because of accidental edit

### ISSUE THREAD

**Issue by Variiuz** [education/GitHubGraduation-2021#9463]
Idk what happened but my PR got closed and said I removed the main branch in my forked repo, as I am under 5000 (#4117) is there something you guys can do?

**Comment by Variiuz** [comment]
I made a new one #9467 can it can be merged instead of my #4117?

**Comment by Variiuz** [comment]
Tagging @juanpflores maybe you can give me an answer, as it's almost at my old PR

**Comment by Variiuz** [comment]
Maybe @elisemoe

**Comment by elisemoe** [comment]
Unfortunately we can't merge the two pull requests for swag eligibility. You should be able to re-open and update the initial pull request though!

**Comment by Variiuz** [comment]
I already tried, there is no re open button

**Comment by elisemoe** [comment]
Ah, I see what you mean. That's a limitation of the repository being public 😞 I'll merge your most recent PR as you're not able to update the first one.
