### ISSUE TITLE
PR Run Failed Due To Student Developer Pack

### ISSUE THREAD

**Issue by Utsav1999** [education/GitHubGraduation-2021#9508]
Hello,

I have applied for the GitHub Student Developer Pack today and also submitted my PR on this repo. But the PR checks failed due to not having student developer pack. Can I know -
- how much time will it take to get approval of the student developer pack?
- If I get approval of the pack, do I need open another PR?

Thank you.

**Comment by anshobrii** [comment]
Yaa, It's the condition  ... that... You have been verified as a student with the GitHub Student Developer Pack for applying in graduation 2021.

**Comment by elisemoe** [comment]
The length of time for approved can depend on a few things. Sometimes we're able to automatically approve, other times we need to do a manual review. Be sure to use the link provided by the bot in the comment on your pull request for priority!
