### ISSUE TITLE
Why you said first come first get ?

### ISSUE THREAD

**Issue by anshobrii** [education/GitHubGraduation-2021#9515]
# Hey, I see the last PR merged is #9000 and much higher PR merged but My PR is #4522 and not yet merged since 2 days ago. Since it follows with first come first serve, is there any chance that my PR is skipped to be merged? Any reasons why?

**Comment by praveenscience** [comment]
I believe your question has been answered in the a previous comment. Do you wanna close it? 🤔 

> @U-c0de @anshobrii The #9000 PR was merged because it is a PR which was created for a PR Against an earlier PR which had an error due to a bug in the BOT

Quoted from the [other issue](https://github.com/education/GitHubGraduation-2021/issues/9450#issuecomment-841377668).

**Comment by anshobrii** [comment]
> I believe your question has been answered in the a previous comment. Do you wanna close it? 🤔
> 
> > @U-c0de @anshobrii The #9000 PR was merged because it is a PR which was created for a PR Against an earlier PR which had an error due to a bug in the BOT
> 
> Quoted from the [other issue](https://github.com/education/GitHubGraduation-2021/issues/9450#issuecomment-841377668).

Sure and thanks

**Comment by praveenscience** [comment]
You're welcome! I guess @vp1099 and @elisemoe are doing a great job! 🔥
