### ISSUE TITLE
Why my pull request isn't merged yet

### ISSUE THREAD

**Issue by Neenu-12** [education/GitHubGraduation-2021#9541]
It's been around more than two days and my PR is ready to merge but there's no response please review it.

**Comment by Luximo** [comment]
What's your PR number?

**Comment by Neenu-12** [comment]
It's #4613

**Comment by BajajAyush** [comment]
Already merged

**Comment by Neenu-12** [comment]
Am I in first 5k ???

**Comment by BajajAyush** [comment]
Yes as there are only about 3600 merged files TN

**Comment by BajajAyush** [comment]
> Yes as there are only about 3600 merged files rn
![55613A5A-CAC5-4C66-8B6A-DF485F091D4F](https://user-images.githubusercontent.com/68808280/118317634-eec8a680-b515-11eb-85e5-7f94b443d723.jpeg)
To be sure check you your mail. You must have received a mail like this

**Comment by Neenu-12** [comment]
Ok, thanks.

**Comment by Neenu-12** [comment]
Ya I got it

**Comment by MColorado** [comment]
@BajajAyush Could you please merge mine as well? #7995
