### ISSUE TITLE
Closed PR by mistake

### ISSUE THREAD

**Issue by Tech-AJ** [education/GitHubGraduation-2021#9589]
I created PR #7563 but it was taking too long to pass checks by bot. I closed PR and resubmitted the same, it got accepted by bot but was assigned PR #7626. 
Please consider the earlier PR #7563 while manual verification .

**Comment by elisemoe** [comment]
Hi @Tech-AJ 👋  please re-open your first pull request and confirm it's "ready to merge" by re-requesting a review by the bot to be considered for the earlier PR.

**Comment by elisemoe** [comment]
I've closed your later PR and manually re-opened the old PR for review.
