### ISSUE TITLE
PR merged but unable to see my folder and file in the repo #5379

### ISSUE THREAD

**Issue by ignitor07** [education/GitHubGraduation-2021#9630]
Hello @vp1099 @elisemoe @juanpflores 

My PR has been merged #5379 but I am unable to see my folder and data in the repo. Can you please tell me the issue? Do I need to do something regarding it or it is completely fine?
Thanks guys:)

**Comment by arghyadeep99** [comment]
![image](https://user-images.githubusercontent.com/33197180/118322017-191d6280-b51c-11eb-8540-5e3d7105cb35.png)


Because of this. Don't worry, your PR is merged, which means you're in!

**Comment by sudo-rahul25** [comment]
> ![image](https://user-images.githubusercontent.com/33197180/118322017-191d6280-b51c-11eb-8540-5e3d7105cb35.png)
> 
> Because of this. Don't worry, your PR is merged, which means you're in!

Thanks @arghyadeep99 😊 but earlier also I saw this issue with some other peeps and admins told them to raise a new PR so just asking is it not my case 😅

**Comment by ignitor07** [comment]
@arghyadeep99 Thanks  but earlier I saw some guys faced the same problem and they were told by admins to raise a new PR. So I hope it is my case, just confirming.

**Comment by diksham1** [comment]
Your PR is part of the repo. It's just not shown because of the limit. You can access it [here](https://github.com/education/GitHubGraduation-2021/tree/main/_data/ignitor07).

**Comment by arrbxr** [comment]
@diksham1 can I get swag, my PR is #5932 ?

**Comment by diksham1** [comment]
> Congratulations on graduating mortar_boardtada. Your submission has been approved and you're now part of the class of 2021! We will send you a package| email with swag to your home. Stay tuned for updates through our social media accounts.

@arrbxr Your PR has been merged. All merged PRs will get swag.

**Comment by arrbxr** [comment]
@diksham1 thank you, mam. And another question how can I update my shipping address?

**Comment by elisemoe** [comment]
> @diksham1 thank you, mam. And another question how can I update my shipping address?

I've emailed you to update your shipping address.

**Comment by elisemoe** [comment]
> Hello @vp1099 @elisemoe @juanpflores
> 
> My PR has been merged #5379 but I am unable to see my folder and data in the repo. Can you please tell me the issue? Do I need to do something regarding it or it is completely fine?
> Thanks guys:)

You've been added you yearbook! If you clone the repository to your local machine, you'll be able to see your folder 💖
