### ISSUE TITLE
Earlier PR was not recognized, new PR exceeds 5000 count, what to do?

### ISSUE THREAD

**Issue by arghyadeep99** [education/GitHubGraduation-2021#9678]
My request wasn't verified by Github Bot (with the Ready To Merge label) hence I had closed #3097 and opened a new one at #6759. However, I am not sure if I will make the cut, due to an error from Github Bot, because this one stands at #6759 which is > 5000, though I had originally made the right submission within 5000. How do I remedy this situation, since we aren't allowed to tag the reviewers in PR as per the checklist?

EDIT: Requesting @elisemoe to kindly review them both and merge the appropriate PR. Thanks!

**Comment by chirag-jn** [comment]
Not all PRs closed have been merged.  You can look at the merged pull requests by following this [link](https://github.com/education/GitHubGraduation-2021/pulls?q=is%3Apr+is%3Aclosed+is%3Amerged)
However note that a lot of PRs are actually reverted PRs. Hence number of accepted users would be less at the moment.

**Comment by arghyadeep99** [comment]
> Not all PRs closed have been merged. You can look at the merged pull requests by following this [link](https://github.com/education/GitHubGraduation-2021/pulls?q=is%3Apr+is%3Aclosed+is%3Amerged)
> However note that a lot of PRs are actually reverted PRs. Hence number of accepted users would be less at the moment.

Yep, I did, but my point is, it seems I may miss the cut. They may not come down to #6759. However, I was pushed out of the line due to the Github Actions error, not my fault.

**Comment by diksham1** [comment]
You can tag the reviewers here. So far, they have merged PRs where the old PR had some bot issue but the new PR exceeded 5000 (See #9000)

**Comment by arghyadeep99** [comment]
Oh great, so I would request @elsiemoe to kindly review this and compare #3097 and #6759 to help me with the issue and merge the PR. Thank you.

**Comment by elisemoe** [comment]
Looks like you've been merged 💖 congrats!
