### ISSUE TITLE
Infinite mails!

### ISSUE THREAD

**Issue by Abhi-Dey** [education/GitHubGraduation-2021#9698]
I'm receiving innumerable mails everytime anyone commits to the the repo. Anyone can tell how to stop these?!!

**Comment by Zeryther** [comment]
You're watching the repository: https://github.com/education/GitHubGraduation-2021/watchers

Try unwatching by clicking the button in the top right

**Comment by elisemoe** [comment]
> You're watching the repository: https://github.com/education/GitHubGraduation-2021/watchers
> 
> Try unwatching by clicking the button in the top right

As mentioned by @Zeryther, you can unwatch the repository. You can also update your GitHub notification settings or unfollow specific Issues if you've been tagged in a thread. Good luck!
