### ISSUE TITLE
My Pr is Merged but Not Showing in _data Folder :cry: 

### ISSUE THREAD

**Issue by adityakumar48** [education/GitHubGraduation-2021#9782]
My Pr is #6854 Merged but Not Showing in _data Folder :cry:

**Comment by idinium96** [comment]
it's just too many. Just clone this repo on your local machine and check it.
`git clone https://github.com/education/GitHubGraduation-2021`

**Comment by adityakumar48** [comment]
I Cloned and Checked but there is no folder at my Name :cry:

**Comment by adityakumar48** [comment]
@idinium96 Thank You I can See My Folder :+1:  :heart:
