### ISSUE TITLE
I guess, my pull request is not yet merged, may I know the reason plz?It's been in ready to merge for 2 days !

### ISSUE THREAD

**Issue by muneersyed156** [education/GitHubGraduation-2021#9784]
I guess, my pull request is not yet merged, may I know the reason plz?It's been in ready to merge for 2 days !

_Originally posted by @muneersyed156 in https://github.com/education/GitHubGraduation-2021/pull/7534#issuecomment-841591467_

**Comment by Ashu-1309** [comment]
Only first 5000 PRs were supposed to be merge that's why !!!

**Comment by adityaj48** [comment]
Mine got merged this morning only, so have patience

**Comment by muneersyed156** [comment]
@Ashu-1309 but I have submitted it 2 days back and got ready to merge on the same day

**Comment by Hamdrive** [comment]
could someone explain why I didnt get merged, my position was #62xx but I got pushed to #8xxx?

**Comment by asangam** [comment]
Mine was [#7599 ](https://github.com/education/GitHubGraduation-2021/pull/7599) I think, I was little too late. There is always a next time.

**Comment by Ashu-1309** [comment]
Only first 5000 PR were supposed to merge so technically you are late .

**Comment by urmilshroff** [comment]
> Only first 5000 PR were supposed to merge so technically you are late .

No, all PRs submitted before 27th May will be reviewed by the GH team. They'll resume work after the weekend, so don't expect anything to be merged until Monday. Check [this](https://github.com/education/GitHubGraduation-2021#may-14-2021).

> Our team is offline this weekend and will be back, on Monday (PT)
> We will review all pull requests submitted before May 27 at 12:00pm PT

**Comment by GliderFromNorth** [comment]
> 
> 
> could someone explain why I didnt get merged, my position was #62xx but I got pushed to #8xxx?
> I had merged 2 days ago

their would be some chnges needed, I should be possible reason.

**Comment by elisemoe** [comment]
Our team will get through all pull requests with the “ready to merge” label before May 27 ✨
