### ISSUE TITLE
My student developer is taking long to get approval

### ISSUE THREAD

**Issue by meghanasarikonda** [education/GitHubGraduation-2021#9841]
I submitted the student developer pack application but it's taking longer for reviewing from your end. It's still pending review and I have applied multiple times, but no luck:(

**Comment by bhawesh2002** [comment]
@meghanasarikonda  when I applied for student developer pack it took about a week to get  any respond from github.
Be patient ...............

**Comment by meghanasarikonda** [comment]
okay @bhawesh2002. Thanks for the information.

**Comment by StarTrooper08** [comment]
I m in same state as the @meghanasarikonda .
The developer pack is still in pending state . 
Our college don't provide us edu email but I applied for developer pack with proper college details but still it's pending for approval.
I had applied for developer pack on 15 April 2021.

Please help me out I just want to have great time joining GitHub Graduation 2021.

**Comment by bhawesh2002** [comment]
@StarTrooper08
Now you will not be able to join GitHub graduation 2021 as of now.
But still apply for GitHub education as you will be able to apply for GitHub graduation for the next year.
If it takes too long keep re-applying and make sure to fill correct information along with the proof of being in the collage

**Comment by StarTrooper08** [comment]
Ok

**Comment by StarTrooper08** [comment]
I just don't have developer pack I have GitHub Education account ready.

**Comment by meghanasarikonda** [comment]
Thanks for the clarification. I didn't get my graduation approval due to this time taking process of approving student developer pack although I made a pull request pretty early. 

So probably I'll try next time. Thanks everyone and it's a great initiative from GitHub, really appreciate it 👍

**Comment by StarTrooper08** [comment]
Can we make pull request right now??
Even if we don't have developer pack!!

**Comment by bhawesh2002** [comment]
@StarTrooper08 
You need to have student developer pack to be able to request a PR.
But still apply for the student developer pack as it has a lot of benifits and you can apply for GitHub graduation next year.

**Comment by StarTrooper08** [comment]
I got my student Developer pack.
Can I apply for GitHub Graduation now??

**Comment by bhawesh2002** [comment]
No you cant apply now for graduation as applications have been closed on 27th of May and tomorrow is the day of graduation.
You can try next year...
Best of Luck
