### ISSUE TITLE
Student developer pack.

### ISSUE THREAD

**Issue by imLaGN** [education/GitHubGraduation-2021#9884]
Hi I already got approved for the Student developer pack 2 times but I received a response saying I don't have a valid Student developer pack approval.

![image](https://user-images.githubusercontent.com/45304574/118360278-f3ce3a00-b597-11eb-8ba0-306e53db803b.png)

**Comment by Sammcb** [comment]
If you have multiple emails for your account, I think you have to make the commit with the email you used to register for the SDP. I was able to just make another commit to my PR with my school email and then the bot approved my PR.
