### ISSUE TITLE
Merge Request taking too long

### ISSUE THREAD

**Issue by Bhavuk-Garg** [education/GitHubGraduation-2021#9889]
Bot showed me institute name should be less than 59 characters. So after update and push, new request showing "waiting for result" for too long. Does it normally take this long

**Comment by Ruqhaiya** [comment]
Hi @Bhavuk-Garg , It takes time, have patience, they'll review it once again. The deadline to be a part of graduation is May 27th. So don't worry, give it a few days. My PR took 2-3 days to get merged. 
Hope this helps!

**Comment by Bhavuk-Garg** [comment]
Okay, Thanks for replying.

**Comment by Ruqhaiya** [comment]
My pleasure!
