### ISSUE TITLE
Bot issue: PR #2054 was closed and PR #8946 was opened for that.

### ISSUE THREAD

**Issue by vasudev-sharma** [education/GitHubGraduation-2021#9913]
My PR is #2054. So, this PR was supposed to reviewed serially for the swag as it falls under **5000**, but due to the weird behavior of the bot, I closed this PR and reopened another PR #8946. I kindly request you to look into it.

 Recently, I noticed the bot issue has been fixed but I'm unable to reopen my PR #2054 now.
 
 
 I kindly request the maintainers to either look at PR #2054 or #8964 as I do qualify for the swag according to the guidelines.

**Comment by merrcury** [comment]
Fill this up -> https://airtable.com/shrZuXu2OKrxO6PiD

**Comment by vs74** [comment]
Indeed I closed the PR myselff due to the bot issue as I wasn't getting "Ready to merge" label even after waiting for 1 day.

So, I figured out that this was a bot issue and closed PR #2054 and reopened another PR #8946 for that.

**Comment by merrcury** [comment]
After making changes in the file You have to re-request review from the bot to get the "Ready to merge" label.

**Comment by vs74** [comment]
> After making changes in the file You have to re-request review from the bot to get the "Ready to merge" label.

There were no instructions mentioned in either the `Readme.md` or anywhere on how to use bot. Had I known that, I would have done that.
