### ISSUE TITLE
PR still not merged 

### ISSUE THREAD

**Issue by arpitjjw** [education/GitHubGraduation-2021#9977]
It has been more than 3 days and my PR #8001 is not merged till now. My PR was approved instantly by the bot though. I have seen recent PRs getting closed but not mine.

**Comment by KaustubhDamania** [comment]
Same here

**Comment by nitish-awasthi** [comment]
Hi @arpitjjw , The last PR that was able to make its place in 5000 was 7383.

**Comment by arpitjjw** [comment]
No, I think #7686 was the last, also #8661 and #8232 were merged before mine but did not get the SWAG though

**Comment by naiiytom** [comment]
Mine is https://github.com/education/GitHubGraduation-2021/pull/7401 and still not merge though.

**Comment by merrcury** [comment]
GitHub Education Team is on holiday and will start reviewing them on Friday if You have submitted them on 14 May or before for Swag Eligibility. For Yearbook, They still are merging those but will take time

**Comment by codeOraaange** [comment]
Hi @merrcury where can I get the latest info from? Because the last information was on the 14th that GitHub Education Team is offline this weekend and will be back, on Monday (PT).

**Comment by merrcury** [comment]
They'll update it in the readme.

**Comment by elisemoe** [comment]
Our team will get through all pull requests with the “ready to merge” label before May 27 ✨
