### ISSUE TITLE
Ready-to-merge PR not merged since past 3 days

### ISSUE THREAD

**Issue by KaustubhDamania** [education/GitHubGraduation-2021#9992]
My [Pull Request](https://github.com/education/GitHubGraduation-2021/pull/7938) has not been merged since the past 3 days. It has been approved by the GitHub Education Bot and the number of merged PRs was less than 5000 at the time of making that PR.

**Comment by merrcury** [comment]
GitHub Education Team is on holiday and will start reviewing them on Friday if You have submitted them on 14 May or before for Swag Eligibility. For Yearbook, They still are merging those but will take time

**Comment by elisemoe** [comment]
Our team will get through all pull requests with the “ready to merge” label before May 27 ✨
